[workspace]
resolver = "2"
members = [
    "crates/lsharp-syntax",
    "crates/lsharp-types",
    "crates/lsharp-ir",
    "crates/lsharp-wasm",
    "crates/lsharp-driver",
    "crates/lsharp-docs",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
miette = { version = "7", features = ["fancy"] }
thiserror = "2"
insta = "1"
clap = { version = "4", features = ["derive"] }
wasm-encoder = "0.245"
wasmtime = "29"
wasmtime-wasi = "29"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
