(module TypeInferDefn)
(import AST)
(import Type)
(import TypeScheme)
(import TypeInferCore)

;; TypeInferDefn.ls - 大規模 covered-slice 型推論関数群
;;
;; infer-lambda, infer-apply, infer-do, infer-defn を含む。
;; これらは infer-expr と相互再帰するが、連結コンパイル時にはグローバル解決される。

;; lambda 式の型推論
;; [8, param-count, param-hash1, ..., body]
;; compile-safe な covered slice として 0/1/2/3/4 引数を扱う
(defn infer-lambda [node env subst counter]
  (let [param-count (vector-get node 1)]
    (if (= param-count 0)
      (let [body-node (vector-get node 2)
            body-result (infer-expr body-node env subst counter)]
        (if (= (result-failed body-result) 1)
          (make-error-result)
          (let [s1 (result-subst body-result)
                body-ty (result-type body-result)
                fun-ty (mk-fun (mk-unit) body-ty)]
            (make-result s1 fun-ty))))
      (if (= param-count 1)
        (let [param-hash (vector-get node 2)
              body-node (vector-get node 3)
              param-ty (fresh-type-var counter)
              param-scheme (mono param-ty)
              new-env (type-env-insert env param-hash param-scheme)
              body-result (infer-expr body-node new-env subst counter)]
          (if (= (result-failed body-result) 1)
            (make-error-result)
            (let [s1 (result-subst body-result)
                  body-ty (result-type body-result)
                  fun-ty (mk-fun (apply-subst s1 param-ty) body-ty)]
              (make-result s1 fun-ty))))
        (if (= param-count 2)
          (let [param1-hash (vector-get node 2)
                param2-hash (vector-get node 3)
                body-node (vector-get node 4)
                param1-ty (fresh-type-var counter)
                param2-ty (fresh-type-var counter)
                env1 (type-env-insert env param1-hash (mono param1-ty))
                env2 (type-env-insert env1 param2-hash (mono param2-ty))
                body-result (infer-expr body-node env2 subst counter)]
            (if (= (result-failed body-result) 1)
              (make-error-result)
              (let [s1 (result-subst body-result)
                    body-ty (result-type body-result)
                    inner-fun (mk-fun (apply-subst s1 param2-ty) body-ty)
                    fun-ty (mk-fun (apply-subst s1 param1-ty) inner-fun)]
                (make-result s1 fun-ty))))
          (if (= param-count 3)
            (let [param1-hash (vector-get node 2)
                  param2-hash (vector-get node 3)
                  param3-hash (vector-get node 4)
                  body-node (vector-get node 5)
                  param1-ty (fresh-type-var counter)
                  param2-ty (fresh-type-var counter)
                  param3-ty (fresh-type-var counter)
                  env1 (type-env-insert env param1-hash (mono param1-ty))
                  env2 (type-env-insert env1 param2-hash (mono param2-ty))
                  env3 (type-env-insert env2 param3-hash (mono param3-ty))
                  body-result (infer-expr body-node env3 subst counter)]
              (if (= (result-failed body-result) 1)
                (make-error-result)
                (let [s1 (result-subst body-result)
                      body-ty (result-type body-result)
                      fun3 (mk-fun (apply-subst s1 param3-ty) body-ty)
                      fun2 (mk-fun (apply-subst s1 param2-ty) fun3)
                      fun1 (mk-fun (apply-subst s1 param1-ty) fun2)]
                  (make-result s1 fun1))))
            (if (= param-count 4)
              (let [param1-hash (vector-get node 2)
                    param2-hash (vector-get node 3)
                    param3-hash (vector-get node 4)
                    param4-hash (vector-get node 5)
                    body-node (vector-get node 6)
                    param1-ty (fresh-type-var counter)
                    param2-ty (fresh-type-var counter)
                    param3-ty (fresh-type-var counter)
                    param4-ty (fresh-type-var counter)
                    env1 (type-env-insert env param1-hash (mono param1-ty))
                    env2 (type-env-insert env1 param2-hash (mono param2-ty))
                    env3 (type-env-insert env2 param3-hash (mono param3-ty))
                    env4 (type-env-insert env3 param4-hash (mono param4-ty))
                    body-result (infer-expr body-node env4 subst counter)]
                (if (= (result-failed body-result) 1)
                  (make-error-result)
                  (let [s1 (result-subst body-result)
                        body-ty (result-type body-result)
                        fun4 (mk-fun (apply-subst s1 param4-ty) body-ty)
                        fun3 (mk-fun (apply-subst s1 param3-ty) fun4)
                        fun2 (mk-fun (apply-subst s1 param2-ty) fun3)
                        fun1 (mk-fun (apply-subst s1 param1-ty) fun2)]
                    (make-result s1 fun1))))
              (if (= param-count 5)
                (let [param1-hash (vector-get node 2)
                      param2-hash (vector-get node 3)
                      param3-hash (vector-get node 4)
                      param4-hash (vector-get node 5)
                      param5-hash (vector-get node 6)
                      body-node (vector-get node 7)
                      param1-ty (fresh-type-var counter)
                      param2-ty (fresh-type-var counter)
                      param3-ty (fresh-type-var counter)
                      param4-ty (fresh-type-var counter)
                      param5-ty (fresh-type-var counter)
                      env1 (type-env-insert env param1-hash (mono param1-ty))
                      env2 (type-env-insert env1 param2-hash (mono param2-ty))
                      env3 (type-env-insert env2 param3-hash (mono param3-ty))
                      env4 (type-env-insert env3 param4-hash (mono param4-ty))
                      env5 (type-env-insert env4 param5-hash (mono param5-ty))
                      body-result (infer-expr body-node env5 subst counter)]
                  (if (= (result-failed body-result) 1)
                    (make-error-result)
                    (let [s1 (result-subst body-result)
                          body-ty (result-type body-result)
                          fun5 (mk-fun (apply-subst s1 param5-ty) body-ty)
                          fun4 (mk-fun (apply-subst s1 param4-ty) fun5)
                          fun3 (mk-fun (apply-subst s1 param3-ty) fun4)
                          fun2 (mk-fun (apply-subst s1 param2-ty) fun3)
                          fun1 (mk-fun (apply-subst s1 param1-ty) fun2)]
                      (make-result s1 fun1))))
                (if (= param-count 6)
                  (let [param1-hash (vector-get node 2)
                        param2-hash (vector-get node 3)
                        param3-hash (vector-get node 4)
                        param4-hash (vector-get node 5)
                        param5-hash (vector-get node 6)
                        param6-hash (vector-get node 7)
                        body-node (vector-get node 8)
                        param1-ty (fresh-type-var counter)
                        param2-ty (fresh-type-var counter)
                        param3-ty (fresh-type-var counter)
                        param4-ty (fresh-type-var counter)
                        param5-ty (fresh-type-var counter)
                        param6-ty (fresh-type-var counter)
                        env1 (type-env-insert env param1-hash (mono param1-ty))
                        env2 (type-env-insert env1 param2-hash (mono param2-ty))
                        env3 (type-env-insert env2 param3-hash (mono param3-ty))
                        env4 (type-env-insert env3 param4-hash (mono param4-ty))
                        env5 (type-env-insert env4 param5-hash (mono param5-ty))
                        env6 (type-env-insert env5 param6-hash (mono param6-ty))
                        body-result (infer-expr body-node env6 subst counter)]
                    (if (= (result-failed body-result) 1)
                      (make-error-result)
                      (let [s1 (result-subst body-result)
                            body-ty (result-type body-result)
                            fun6 (mk-fun (apply-subst s1 param6-ty) body-ty)
                            fun5 (mk-fun (apply-subst s1 param5-ty) fun6)
                            fun4 (mk-fun (apply-subst s1 param4-ty) fun5)
                            fun3 (mk-fun (apply-subst s1 param3-ty) fun4)
                            fun2 (mk-fun (apply-subst s1 param2-ty) fun3)
                            fun1 (mk-fun (apply-subst s1 param1-ty) fun2)]
                        (make-result s1 fun1))))
                (if (= param-count 7)
                  (let [param1-hash (vector-get node 2)
                        param2-hash (vector-get node 3)
                        param3-hash (vector-get node 4)
                        param4-hash (vector-get node 5)
                        param5-hash (vector-get node 6)
                        param6-hash (vector-get node 7)
                        param7-hash (vector-get node 8)
                        body-node (vector-get node 9)
                        param1-ty (fresh-type-var counter)
                        param2-ty (fresh-type-var counter)
                        param3-ty (fresh-type-var counter)
                        param4-ty (fresh-type-var counter)
                        param5-ty (fresh-type-var counter)
                        param6-ty (fresh-type-var counter)
                        param7-ty (fresh-type-var counter)
                        env1 (type-env-insert env param1-hash (mono param1-ty))
                        env2 (type-env-insert env1 param2-hash (mono param2-ty))
                        env3 (type-env-insert env2 param3-hash (mono param3-ty))
                        env4 (type-env-insert env3 param4-hash (mono param4-ty))
                        env5 (type-env-insert env4 param5-hash (mono param5-ty))
                        env6 (type-env-insert env5 param6-hash (mono param6-ty))
                        env7 (type-env-insert env6 param7-hash (mono param7-ty))
                        body-result (infer-expr body-node env7 subst counter)]
                    (if (= (result-failed body-result) 1)
                      (make-error-result)
                      (let [s1 (result-subst body-result)
                            body-ty (result-type body-result)
                            fun7 (mk-fun (apply-subst s1 param7-ty) body-ty)
                            fun6 (mk-fun (apply-subst s1 param6-ty) fun7)
                            fun5 (mk-fun (apply-subst s1 param5-ty) fun6)
                            fun4 (mk-fun (apply-subst s1 param4-ty) fun5)
                            fun3 (mk-fun (apply-subst s1 param3-ty) fun4)
                            fun2 (mk-fun (apply-subst s1 param2-ty) fun3)
                            fun1 (mk-fun (apply-subst s1 param1-ty) fun2)]
                        (make-result s1 fun1))))
                  (make-error-result)))))))))))

;; 関数適用の型推論
;; [5, func-node, arg-count, arg1, arg2, ...]
;; compile-safe な covered slice として 0-4 引数を扱う
(defn infer-apply [node env subst counter]
  (let [func-node (vector-get node 1)
        argc (vector-get node 2)]
    (if (= argc 0)
      ;; 引数なし: func を推論してそのまま返す
      (infer-expr func-node env subst counter)
      (let [func-result (infer-expr func-node env subst counter)]
        (if (= (result-failed func-result) 1)
          (make-error-result)
          (let [s1 (result-subst func-result)
                func-ty (result-type func-result)]
            (if (= argc 1)
              ;; 1 引数の適用
              (let [arg1-result (infer-expr (vector-get node 3) env s1 counter)]
                (if (= (result-failed arg1-result) 1)
                  (make-error-result)
                  (let [s2 (result-subst arg1-result)
                        arg1-ty (result-type arg1-result)
                        ret-ty (fresh-type-var counter)
                        expected (mk-fun arg1-ty ret-ty)
                        s3 (unify (apply-subst s2 func-ty) expected s2)]
                    (if (= (unify-failed s3) 1)
                      (make-error-result)
                      (make-result s3 (apply-subst s3 ret-ty))))))
              (if (= argc 2)
                ;; 2 引数の適用
                (let [arg1-result (infer-expr (vector-get node 3) env s1 counter)]
                  (if (= (result-failed arg1-result) 1)
                    (make-error-result)
                    (let [s2 (result-subst arg1-result)
                          arg1-ty (result-type arg1-result)
                          arg2-result (infer-expr (vector-get node 4) env s2 counter)]
                      (if (= (result-failed arg2-result) 1)
                        (make-error-result)
                        (let [s3 (result-subst arg2-result)
                              arg2-ty (result-type arg2-result)
                              ret-ty (fresh-type-var counter)
                              expected (mk-fun arg1-ty (mk-fun arg2-ty ret-ty))
                              s4 (unify (apply-subst s3 func-ty) expected s3)]
                          (if (= (unify-failed s4) 1)
                            (make-error-result)
                            (make-result s4 (apply-subst s4 ret-ty))))))))
                (if (= argc 3)
                  ;; 3 引数の適用
                  (let [arg1-result (infer-expr (vector-get node 3) env s1 counter)]
                    (if (= (result-failed arg1-result) 1)
                      (make-error-result)
                      (let [s2 (result-subst arg1-result)
                            arg1-ty (result-type arg1-result)
                            arg2-result (infer-expr (vector-get node 4) env s2 counter)]
                        (if (= (result-failed arg2-result) 1)
                          (make-error-result)
                          (let [s3 (result-subst arg2-result)
                                arg2-ty (result-type arg2-result)
                                arg3-result (infer-expr (vector-get node 5) env s3 counter)]
                            (if (= (result-failed arg3-result) 1)
                              (make-error-result)
                              (let [s4 (result-subst arg3-result)
                                    arg3-ty (result-type arg3-result)
                                    ret-ty (fresh-type-var counter)
                                    expected (mk-fun arg1-ty (mk-fun arg2-ty (mk-fun arg3-ty ret-ty)))
                                    s5 (unify (apply-subst s4 func-ty) expected s4)]
                                (if (= (unify-failed s5) 1)
                                  (make-error-result)
                                  (make-result s5 (apply-subst s5 ret-ty))))))))))
                  (if (= argc 4)
                    ;; 4 引数の適用
                    (let [arg1-result (infer-expr (vector-get node 3) env s1 counter)]
                      (if (= (result-failed arg1-result) 1)
                        (make-error-result)
                        (let [s2 (result-subst arg1-result)
                              arg1-ty (result-type arg1-result)
                              arg2-result (infer-expr (vector-get node 4) env s2 counter)]
                          (if (= (result-failed arg2-result) 1)
                            (make-error-result)
                            (let [s3 (result-subst arg2-result)
                                  arg2-ty (result-type arg2-result)
                                  arg3-result (infer-expr (vector-get node 5) env s3 counter)]
                              (if (= (result-failed arg3-result) 1)
                                (make-error-result)
                                (let [s4 (result-subst arg3-result)
                                      arg3-ty (result-type arg3-result)
                                      arg4-result (infer-expr (vector-get node 6) env s4 counter)]
                                  (if (= (result-failed arg4-result) 1)
                                    (make-error-result)
                                    (let [s5 (result-subst arg4-result)
                                          arg4-ty (result-type arg4-result)
                                          ret-ty (fresh-type-var counter)
                                          expected (mk-fun arg1-ty (mk-fun arg2-ty (mk-fun arg3-ty (mk-fun arg4-ty ret-ty))))
                                          s6 (unify (apply-subst s5 func-ty) expected s5)]
                                      (if (= (unify-failed s6) 1)
                                        (make-error-result)
                                        (make-result s6 (apply-subst s6 ret-ty))))))))))))
                    (if (= argc 5)
                      ;; 5 引数の適用
                      (let [arg1-result (infer-expr (vector-get node 3) env s1 counter)]
                        (if (= (result-failed arg1-result) 1)
                          (make-error-result)
                          (let [s2 (result-subst arg1-result)
                                arg1-ty (result-type arg1-result)
                                arg2-result (infer-expr (vector-get node 4) env s2 counter)]
                            (if (= (result-failed arg2-result) 1)
                              (make-error-result)
                              (let [s3 (result-subst arg2-result)
                                    arg2-ty (result-type arg2-result)
                                    arg3-result (infer-expr (vector-get node 5) env s3 counter)]
                                (if (= (result-failed arg3-result) 1)
                                  (make-error-result)
                                  (let [s4 (result-subst arg3-result)
                                        arg3-ty (result-type arg3-result)
                                        arg4-result (infer-expr (vector-get node 6) env s4 counter)]
                                    (if (= (result-failed arg4-result) 1)
                                      (make-error-result)
                                      (let [s5 (result-subst arg4-result)
                                            arg4-ty (result-type arg4-result)
                                            arg5-result (infer-expr (vector-get node 7) env s5 counter)]
                                        (if (= (result-failed arg5-result) 1)
                                          (make-error-result)
                                          (let [s6 (result-subst arg5-result)
                                                arg5-ty (result-type arg5-result)
                                                ret-ty (fresh-type-var counter)
                                                expected (mk-fun arg1-ty (mk-fun arg2-ty (mk-fun arg3-ty (mk-fun arg4-ty (mk-fun arg5-ty ret-ty)))))
                                                s7 (unify (apply-subst s6 func-ty) expected s6)]
                                            (if (= (unify-failed s7) 1)
                                              (make-error-result)
                                              (make-result s7 (apply-subst s7 ret-ty))))))))))))))
                      (if (= argc 6)
                        ;; 6 引数の適用
                        (let [arg1-result (infer-expr (vector-get node 3) env s1 counter)]
                          (if (= (result-failed arg1-result) 1)
                            (make-error-result)
                            (let [s2 (result-subst arg1-result)
                                  arg1-ty (result-type arg1-result)
                                  arg2-result (infer-expr (vector-get node 4) env s2 counter)]
                              (if (= (result-failed arg2-result) 1)
                                (make-error-result)
                                (let [s3 (result-subst arg2-result)
                                      arg2-ty (result-type arg2-result)
                                      arg3-result (infer-expr (vector-get node 5) env s3 counter)]
                                  (if (= (result-failed arg3-result) 1)
                                    (make-error-result)
                                    (let [s4 (result-subst arg3-result)
                                          arg3-ty (result-type arg3-result)
                                          arg4-result (infer-expr (vector-get node 6) env s4 counter)]
                                      (if (= (result-failed arg4-result) 1)
                                        (make-error-result)
                                        (let [s5 (result-subst arg4-result)
                                              arg4-ty (result-type arg4-result)
                                              arg5-result (infer-expr (vector-get node 7) env s5 counter)]
                                          (if (= (result-failed arg5-result) 1)
                                            (make-error-result)
                                            (let [s6 (result-subst arg5-result)
                                                  arg5-ty (result-type arg5-result)
                                                  arg6-result (infer-expr (vector-get node 8) env s6 counter)]
                                              (if (= (result-failed arg6-result) 1)
                                                (make-error-result)
                                                (let [s7 (result-subst arg6-result)
                                                      arg6-ty (result-type arg6-result)
                                                      ret-ty (fresh-type-var counter)
                                                      expected (mk-fun arg1-ty (mk-fun arg2-ty (mk-fun arg3-ty (mk-fun arg4-ty (mk-fun arg5-ty (mk-fun arg6-ty ret-ty))))))
                                                      s8 (unify (apply-subst s7 func-ty) expected s7)]
                                                  (if (= (unify-failed s8) 1)
                                                    (make-error-result)
                                                    (make-result s8 (apply-subst s8 ret-ty))))))))))))))))
                        (if (= argc 7)
                          ;; 7 引数の適用
                          (let [arg1-result (infer-expr (vector-get node 3) env s1 counter)]
                            (if (= (result-failed arg1-result) 1)
                              (make-error-result)
                              (let [s2 (result-subst arg1-result)
                                    arg1-ty (result-type arg1-result)
                                    arg2-result (infer-expr (vector-get node 4) env s2 counter)]
                                (if (= (result-failed arg2-result) 1)
                                  (make-error-result)
                                  (let [s3 (result-subst arg2-result)
                                        arg2-ty (result-type arg2-result)
                                        arg3-result (infer-expr (vector-get node 5) env s3 counter)]
                                    (if (= (result-failed arg3-result) 1)
                                      (make-error-result)
                                      (let [s4 (result-subst arg3-result)
                                            arg3-ty (result-type arg3-result)
                                            arg4-result (infer-expr (vector-get node 6) env s4 counter)]
                                        (if (= (result-failed arg4-result) 1)
                                          (make-error-result)
                                          (let [s5 (result-subst arg4-result)
                                                arg4-ty (result-type arg4-result)
                                                arg5-result (infer-expr (vector-get node 7) env s5 counter)]
                                            (if (= (result-failed arg5-result) 1)
                                              (make-error-result)
                                              (let [s6 (result-subst arg5-result)
                                                    arg5-ty (result-type arg5-result)
                                                    arg6-result (infer-expr (vector-get node 8) env s6 counter)]
                                                (if (= (result-failed arg6-result) 1)
                                                  (make-error-result)
                                                  (let [s7 (result-subst arg6-result)
                                                        arg6-ty (result-type arg6-result)
                                                        arg7-result (infer-expr (vector-get node 9) env s7 counter)]
                                                    (if (= (result-failed arg7-result) 1)
                                                      (make-error-result)
                                                      (let [s8 (result-subst arg7-result)
                                                            arg7-ty (result-type arg7-result)
                                                            ret-ty (fresh-type-var counter)
                                                            expected (mk-fun arg1-ty (mk-fun arg2-ty (mk-fun arg3-ty (mk-fun arg4-ty (mk-fun arg5-ty (mk-fun arg6-ty (mk-fun arg7-ty ret-ty)))))))
                                                            s9 (unify (apply-subst s8 func-ty) expected s8)]
                                                        (if (= (unify-failed s9) 1)
                                                          (make-error-result)
                                                          (make-result s9 (apply-subst s9 ret-ty))))))))))))))))))
                          (make-error-result))))))))))))))

;; do ブロックの型推論
;; [9, expr-count, expr1, expr2, ...]
(defn infer-do [node env subst counter]
  (let [ec (vector-get node 1)]
    (if (= ec 0)
      ;; 空の do: Int(0) を返す
      (make-result subst (mk-int))
      (if (= ec 1)
        ;; 1 式
        (infer-expr (vector-get node 2) env subst counter)
        ;; 2 式以上: 各式を順次推論、最後の型を返す
        (let [r1 (infer-expr (vector-get node 2) env subst counter)]
          (if (= (result-failed r1) 1)
            (make-error-result)
            (let [s1 (result-subst r1)]
              (if (= ec 2)
                (infer-expr (vector-get node 3) env s1 counter)
                (let [r2 (infer-expr (vector-get node 3) env s1 counter)]
                  (if (= (result-failed r2) 1)
                    (make-error-result)
                    (let [s2 (result-subst r2)]
                      (if (= ec 3)
                        (infer-expr (vector-get node 4) env s2 counter)
                        (let [r3 (infer-expr (vector-get node 4) env s2 counter)]
                          (if (= (result-failed r3) 1)
                            (make-error-result)
                            (let [s3 (result-subst r3)]
                              (if (= ec 4)
                                (infer-expr (vector-get node 5) env s3 counter)
                                ;; covered slice として 5/6 式を扱う
                                (let [r4 (infer-expr (vector-get node 5) env s3 counter)]
                                  (if (= (result-failed r4) 1)
                                    (make-error-result)
                                    (let [s4 (result-subst r4)]
                                      (if (= ec 5)
                                        (infer-expr (vector-get node 6) env s4 counter)
                                        (if (= ec 6)
                                          (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                            (if (= (result-failed r5) 1)
                                              (make-error-result)
                                              (infer-expr (vector-get node 7) env (result-subst r5) counter)))
                                          (if (= ec 7)
                                            (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                              (if (= (result-failed r5) 1)
                                                (make-error-result)
                                                (let [s5 (result-subst r5)]
                                                  (infer-expr (vector-get node 8) env s5 counter))))
                                            (if (= ec 8)
                                              (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                                (if (= (result-failed r5) 1)
                                                  (make-error-result)
                                                  (let [s5 (result-subst r5)
                                                        r6 (infer-expr (vector-get node 7) env s5 counter)]
                                                    (if (= (result-failed r6) 1)
                                                      (make-error-result)
                                                      (infer-expr (vector-get node 9) env (result-subst r6) counter)))))
                                              (if (= ec 9)
                                                (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                                  (if (= (result-failed r5) 1)
                                                    (make-error-result)
                                                    (let [s5 (result-subst r5)
                                                          r6 (infer-expr (vector-get node 7) env s5 counter)]
                                                      (if (= (result-failed r6) 1)
                                                        (make-error-result)
                                                        (let [s6 (result-subst r6)]
                                                          (infer-expr (vector-get node 10) env s6 counter))))))
                                                (if (= ec 10)
                                                  (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                                    (if (= (result-failed r5) 1)
                                                      (make-error-result)
                                                      (let [s5 (result-subst r5)
                                                            r6 (infer-expr (vector-get node 7) env s5 counter)]
                                                        (if (= (result-failed r6) 1)
                                                          (make-error-result)
                                                          (let [s6 (result-subst r6)
                                                                r7 (infer-expr (vector-get node 8) env s6 counter)]
                                                            (if (= (result-failed r7) 1)
                                                              (make-error-result)
                                                              (infer-expr (vector-get node 11) env (result-subst r7) counter)))))))
                                                  (if (= ec 11)
                                                    (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                                      (if (= (result-failed r5) 1)
                                                        (make-error-result)
                                                        (let [s5 (result-subst r5)
                                                              r6 (infer-expr (vector-get node 7) env s5 counter)]
                                                          (if (= (result-failed r6) 1)
                                                            (make-error-result)
                                                            (let [s6 (result-subst r6)
                                                                  r7 (infer-expr (vector-get node 8) env s6 counter)]
                                                              (if (= (result-failed r7) 1)
                                                                (make-error-result)
                                                                (let [s7 (result-subst r7)
                                                                      r8 (infer-expr (vector-get node 9) env s7 counter)]
                                                                  (if (= (result-failed r8) 1)
                                                                    (make-error-result)
                                                                    (infer-expr (vector-get node 12) env (result-subst r8) counter)))))))))
                                                    (if (= ec 12)
                                                      (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                                        (if (= (result-failed r5) 1)
                                                          (make-error-result)
                                                          (let [s5 (result-subst r5)
                                                                r6 (infer-expr (vector-get node 7) env s5 counter)]
                                                            (if (= (result-failed r6) 1)
                                                              (make-error-result)
                                                              (let [s6 (result-subst r6)
                                                                    r7 (infer-expr (vector-get node 8) env s6 counter)]
                                                                (if (= (result-failed r7) 1)
                                                                  (make-error-result)
                                                                  (let [s7 (result-subst r7)
                                                                        r8 (infer-expr (vector-get node 9) env s7 counter)]
                                                                    (if (= (result-failed r8) 1)
                                                                      (make-error-result)
                                                                      (let [s8 (result-subst r8)
                                                                            r9 (infer-expr (vector-get node 10) env s8 counter)]
                                                                        (if (= (result-failed r9) 1)
                                                                          (make-error-result)
                                                                          (infer-expr (vector-get node 13) env (result-subst r9) counter)))))))))))
                                                      (if (= ec 13)
                                                        (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                                          (if (= (result-failed r5) 1)
                                                            (make-error-result)
                                                            (let [s5 (result-subst r5)
                                                                  r6 (infer-expr (vector-get node 7) env s5 counter)]
                                                              (if (= (result-failed r6) 1)
                                                                (make-error-result)
                                                                (let [s6 (result-subst r6)
                                                                      r7 (infer-expr (vector-get node 8) env s6 counter)]
                                                                  (if (= (result-failed r7) 1)
                                                                    (make-error-result)
                                                                    (let [s7 (result-subst r7)
                                                                          r8 (infer-expr (vector-get node 9) env s7 counter)]
                                                                      (if (= (result-failed r8) 1)
                                                                        (make-error-result)
                                                                        (let [s8 (result-subst r8)
                                                                              r9 (infer-expr (vector-get node 10) env s8 counter)]
                                                                          (if (= (result-failed r9) 1)
                                                                            (make-error-result)
                                                                            (let [s9 (result-subst r9)
                                                                                  r10 (infer-expr (vector-get node 11) env s9 counter)]
                                                                              (if (= (result-failed r10) 1)
                                                                                (make-error-result)
                                                                                (infer-expr (vector-get node 14) env (result-subst r10) counter)))))))))))))
                                                        (if (= ec 14)
                                                          (let [r5 (infer-expr (vector-get node 6) env s4 counter)]
                                                            (if (= (result-failed r5) 1)
                                                              (make-error-result)
                                                              (let [s5 (result-subst r5)
                                                                    r6 (infer-expr (vector-get node 7) env s5 counter)]
                                                                (if (= (result-failed r6) 1)
                                                                  (make-error-result)
                                                                  (let [s6 (result-subst r6)
                                                                        r7 (infer-expr (vector-get node 8) env s6 counter)]
                                                                    (if (= (result-failed r7) 1)
                                                                      (make-error-result)
                                                                      (let [s7 (result-subst r7)
                                                                            r8 (infer-expr (vector-get node 9) env s7 counter)]
                                                                        (if (= (result-failed r8) 1)
                                                                          (make-error-result)
                                                                          (let [s8 (result-subst r8)
                                                                                r9 (infer-expr (vector-get node 10) env s8 counter)]
                                                                            (if (= (result-failed r9) 1)
                                                                              (make-error-result)
                                                                              (let [s9 (result-subst r9)
                                                                                    r10 (infer-expr (vector-get node 11) env s9 counter)]
                                                                                (if (= (result-failed r10) 1)
                                                                                  (make-error-result)
                                                                                  (let [s10 (result-subst r10)
                                                                                        r11 (infer-expr (vector-get node 12) env s10 counter)]
                                                                                    (if (= (result-failed r11) 1)
                                                                                      (make-error-result)
                                                                                      (infer-expr (vector-get node 15) env (result-subst r11) counter)))))))))))))))
                                                          ;; 15 式以上は既存 fallback を維持
                                                          (infer-expr (vector-get node 6) env s4 counter))))))))))))))))))))))))))))))

;; ============================================================
;; infer-defn: トップレベル関数定義の型推論
;; ============================================================
;; [20, name-hash, param-count, param-hash1, ..., body]
;; compile-safe な covered slice として 0/1/2/3/4 引数を扱う

(defn infer-defn [node env counter]
  (let [name-hash (vector-get node 1)
        param-count (vector-get node 2)
        subst (subst-new)]
    (if (= param-count 0)
      (let [body-node (vector-get node 3)
            result (infer-expr body-node env subst counter)]
        (if (= (result-failed result) 1)
          (make-error-result)
          (let [s (result-subst result)
                body-ty (result-type result)
                scheme (generalize (apply-subst s body-ty) (map-new))
                new-env (type-env-insert env name-hash scheme)]
            (vector-push (make-result s (apply-subst s body-ty)) new-env))))
      (if (= param-count 1)
        (let [param-hash (vector-get node 3)
              body-node (vector-get node 4)
              param-ty (fresh-type-var counter)
              env1 (type-env-insert env param-hash (mono param-ty))
              result (infer-expr body-node env1 subst counter)]
          (if (= (result-failed result) 1)
            (make-error-result)
            (let [s (result-subst result)
                  body-ty (result-type result)
                  fun-ty (mk-fun (apply-subst s param-ty) body-ty)
                  scheme (generalize (apply-subst s fun-ty) (map-new))
                  new-env (type-env-insert env name-hash scheme)]
              (vector-push (make-result s (apply-subst s fun-ty)) new-env))))
        (if (= param-count 2)
          (let [param1-hash (vector-get node 3)
                param2-hash (vector-get node 4)
                body-node (vector-get node 5)
                param1-ty (fresh-type-var counter)
                param2-ty (fresh-type-var counter)
                env1 (type-env-insert env param1-hash (mono param1-ty))
                env2 (type-env-insert env1 param2-hash (mono param2-ty))
                result (infer-expr body-node env2 subst counter)]
            (if (= (result-failed result) 1)
              (make-error-result)
              (let [s (result-subst result)
                    body-ty (result-type result)
                    inner-fun (mk-fun (apply-subst s param2-ty) body-ty)
                    fun-ty (mk-fun (apply-subst s param1-ty) inner-fun)
                    scheme (generalize (apply-subst s fun-ty) (map-new))
                    new-env (type-env-insert env name-hash scheme)]
                (vector-push (make-result s (apply-subst s fun-ty)) new-env))))
          (if (= param-count 3)
            (let [param1-hash (vector-get node 3)
                  param2-hash (vector-get node 4)
                  param3-hash (vector-get node 5)
                  body-node (vector-get node 6)
                  param1-ty (fresh-type-var counter)
                  param2-ty (fresh-type-var counter)
                  param3-ty (fresh-type-var counter)
                  env1 (type-env-insert env param1-hash (mono param1-ty))
                  env2 (type-env-insert env1 param2-hash (mono param2-ty))
                  env3 (type-env-insert env2 param3-hash (mono param3-ty))
                  result (infer-expr body-node env3 subst counter)]
              (if (= (result-failed result) 1)
                (make-error-result)
                (let [s (result-subst result)
                      body-ty (result-type result)
                      fun3 (mk-fun (apply-subst s param3-ty) body-ty)
                      fun2 (mk-fun (apply-subst s param2-ty) fun3)
                      fun1 (mk-fun (apply-subst s param1-ty) fun2)
                      scheme (generalize (apply-subst s fun1) (map-new))
                      new-env (type-env-insert env name-hash scheme)]
                  (vector-push (make-result s (apply-subst s fun1)) new-env))))
            (if (= param-count 4)
              (let [param1-hash (vector-get node 3)
                    param2-hash (vector-get node 4)
                    param3-hash (vector-get node 5)
                    param4-hash (vector-get node 6)
                    body-node (vector-get node 7)
                    param1-ty (fresh-type-var counter)
                    param2-ty (fresh-type-var counter)
                    param3-ty (fresh-type-var counter)
                    param4-ty (fresh-type-var counter)
                    env1 (type-env-insert env param1-hash (mono param1-ty))
                    env2 (type-env-insert env1 param2-hash (mono param2-ty))
                    env3 (type-env-insert env2 param3-hash (mono param3-ty))
                    env4 (type-env-insert env3 param4-hash (mono param4-ty))
                    result (infer-expr body-node env4 subst counter)]
                (if (= (result-failed result) 1)
                  (make-error-result)
                  (let [s (result-subst result)
                        body-ty (result-type result)
                        fun4 (mk-fun (apply-subst s param4-ty) body-ty)
                        fun3 (mk-fun (apply-subst s param3-ty) fun4)
                        fun2 (mk-fun (apply-subst s param2-ty) fun3)
                        fun1 (mk-fun (apply-subst s param1-ty) fun2)
                        scheme (generalize (apply-subst s fun1) (map-new))
                        new-env (type-env-insert env name-hash scheme)]
                    (vector-push (make-result s (apply-subst s fun1)) new-env))))
              (if (= param-count 5)
                (let [param1-hash (vector-get node 3)
                      param2-hash (vector-get node 4)
                      param3-hash (vector-get node 5)
                      param4-hash (vector-get node 6)
                      param5-hash (vector-get node 7)
                      body-node (vector-get node 8)
                      param1-ty (fresh-type-var counter)
                      param2-ty (fresh-type-var counter)
                      param3-ty (fresh-type-var counter)
                      param4-ty (fresh-type-var counter)
                      param5-ty (fresh-type-var counter)
                      env1 (type-env-insert env param1-hash (mono param1-ty))
                      env2 (type-env-insert env1 param2-hash (mono param2-ty))
                      env3 (type-env-insert env2 param3-hash (mono param3-ty))
                      env4 (type-env-insert env3 param4-hash (mono param4-ty))
                      env5 (type-env-insert env4 param5-hash (mono param5-ty))
                      result (infer-expr body-node env5 subst counter)]
                  (if (= (result-failed result) 1)
                    (make-error-result)
                    (let [s (result-subst result)
                          body-ty (result-type result)
                          fun5 (mk-fun (apply-subst s param5-ty) body-ty)
                          fun4 (mk-fun (apply-subst s param4-ty) fun5)
                          fun3 (mk-fun (apply-subst s param3-ty) fun4)
                          fun2 (mk-fun (apply-subst s param2-ty) fun3)
                          fun1 (mk-fun (apply-subst s param1-ty) fun2)
                          scheme (generalize (apply-subst s fun1) (map-new))
                          new-env (type-env-insert env name-hash scheme)]
                      (vector-push (make-result s (apply-subst s fun1)) new-env))))
                (if (= param-count 6)
                  (let [param1-hash (vector-get node 3)
                        param2-hash (vector-get node 4)
                        param3-hash (vector-get node 5)
                        param4-hash (vector-get node 6)
                        param5-hash (vector-get node 7)
                        param6-hash (vector-get node 8)
                        body-node (vector-get node 9)
                        param1-ty (fresh-type-var counter)
                        param2-ty (fresh-type-var counter)
                        param3-ty (fresh-type-var counter)
                        param4-ty (fresh-type-var counter)
                        param5-ty (fresh-type-var counter)
                        param6-ty (fresh-type-var counter)
                        env1 (type-env-insert env param1-hash (mono param1-ty))
                        env2 (type-env-insert env1 param2-hash (mono param2-ty))
                        env3 (type-env-insert env2 param3-hash (mono param3-ty))
                        env4 (type-env-insert env3 param4-hash (mono param4-ty))
                        env5 (type-env-insert env4 param5-hash (mono param5-ty))
                        env6 (type-env-insert env5 param6-hash (mono param6-ty))
                        result (infer-expr body-node env6 subst counter)]
                    (if (= (result-failed result) 1)
                      (make-error-result)
                      (let [s (result-subst result)
                            body-ty (result-type result)
                            fun6 (mk-fun (apply-subst s param6-ty) body-ty)
                            fun5 (mk-fun (apply-subst s param5-ty) fun6)
                            fun4 (mk-fun (apply-subst s param4-ty) fun5)
                            fun3 (mk-fun (apply-subst s param3-ty) fun4)
                            fun2 (mk-fun (apply-subst s param2-ty) fun3)
                            fun1 (mk-fun (apply-subst s param1-ty) fun2)
                            scheme (generalize (apply-subst s fun1) (map-new))
                            new-env (type-env-insert env name-hash scheme)]
                        (vector-push (make-result s (apply-subst s fun1)) new-env))))
                  (if (= param-count 7)
                    (let [param1-hash (vector-get node 3)
                          param2-hash (vector-get node 4)
                          param3-hash (vector-get node 5)
                          param4-hash (vector-get node 6)
                          param5-hash (vector-get node 7)
                          param6-hash (vector-get node 8)
                          param7-hash (vector-get node 9)
                          body-node (vector-get node 10)
                          param1-ty (fresh-type-var counter)
                          param2-ty (fresh-type-var counter)
                          param3-ty (fresh-type-var counter)
                          param4-ty (fresh-type-var counter)
                          param5-ty (fresh-type-var counter)
                          param6-ty (fresh-type-var counter)
                          param7-ty (fresh-type-var counter)
                          env1 (type-env-insert env param1-hash (mono param1-ty))
                          env2 (type-env-insert env1 param2-hash (mono param2-ty))
                          env3 (type-env-insert env2 param3-hash (mono param3-ty))
                          env4 (type-env-insert env3 param4-hash (mono param4-ty))
                          env5 (type-env-insert env4 param5-hash (mono param5-ty))
                          env6 (type-env-insert env5 param6-hash (mono param6-ty))
                          env7 (type-env-insert env6 param7-hash (mono param7-ty))
                          result (infer-expr body-node env7 subst counter)]
                      (if (= (result-failed result) 1)
                        (make-error-result)
                        (let [s (result-subst result)
                              body-ty (result-type result)
                              fun7 (mk-fun (apply-subst s param7-ty) body-ty)
                              fun6 (mk-fun (apply-subst s param6-ty) fun7)
                              fun5 (mk-fun (apply-subst s param5-ty) fun6)
                              fun4 (mk-fun (apply-subst s param4-ty) fun5)
                              fun3 (mk-fun (apply-subst s param3-ty) fun4)
                              fun2 (mk-fun (apply-subst s param2-ty) fun3)
                              fun1 (mk-fun (apply-subst s param1-ty) fun2)
                              scheme (generalize (apply-subst s fun1) (map-new))
                              new-env (type-env-insert env name-hash scheme)]
                          (vector-push (make-result s (apply-subst s fun1)) new-env))))
                    (make-error-result)))))))))))
