[package]
name = "lsharp-driver"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lsharp"
path = "src/main.rs"

[dependencies]
lsharp-syntax = { path = "../lsharp-syntax" }
lsharp-types = { path = "../lsharp-types" }
lsharp-tooling = { path = "../lsharp-tooling" }
lsharp-wasm = { path = "../lsharp-wasm" }
lsharp-docs = { path = "../lsharp-docs" }
lsharp-lsp = { path = "../lsharp-lsp" }
clap.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["rt-multi-thread"] }
miette.workspace = true
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
rustyline = "15"
dirs = "6"

[dev-dependencies]
lsharp-syntax = { path = "../lsharp-syntax" }
lsharp-types = { path = "../lsharp-types" }
lsharp-ir = { path = "../lsharp-ir" }
wat = "1"
jsonschema = { version = "0.33", default-features = false }
ed25519-dalek = "2"

[build-dependencies]
lsharp-ir = { path = "../lsharp-ir" }
lsharp-wasm = { path = "../lsharp-wasm" }
