[package]
name = "lsharp-driver"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lsharp"
path = "src/main.rs"

[dependencies]
lsharp-syntax = { path = "../lsharp-syntax" }
lsharp-types = { path = "../lsharp-types" }
lsharp-ir = { path = "../lsharp-ir" }
lsharp-wasm = { path = "../lsharp-wasm" }
lsharp-docs = { path = "../lsharp-docs" }
lsharp-lsp = { path = "../lsharp-lsp" }
clap.workspace = true
tokio = { version = "1", features = ["rt-multi-thread"] }
miette.workspace = true
toml.workspace = true
serde.workspace = true
rustyline = "15"
dirs = "6"
