(module Syntax.AST)
(import Syntax.Token)
(defn ast-lit-int [] 1)
(defn ast-lit-bool [] 2)
(defn ast-lit-string [] 3)
(defn ast-var [] 4)
(defn ast-apply [] 5)
(defn ast-if [] 6)
(defn ast-let [] 7)
(defn ast-lambda [] 8)
(defn ast-do [] 9)
(defn ast-match [] 10)
(defn ast-ann [] 11)
(defn ast-recordlit [] 12)
(defn ast-fieldaccess [] 13)
(defn ast-recordupdate [] 14)
(defn ast-computation [] 15)
(defn ast-quote [] 16)
(defn ast-unquote [] 17)
(defn ast-unquote-splice [] 18)
(defn ast-lit-float [] 19)
(defn ast-lit-unit [] 32)
(defn computation-step-expr [] 0)
(defn computation-step-let-bang [] 1)
(defn computation-step-do-bang [] 2)
(defn computation-step-return [] 3)
(defn ast-defn [] 20)
(defn ast-typedef [] 21)
(defn ast-type-decl [] 21)
(defn ast-recorddef [] 22)
(defn ast-typealias [] 23)
(defn ast-typeconstrained [] 24)
(defn ast-module-decl [] 25)
(defn ast-import-decl [] 26)
(defn ast-traitdef [] 27)
(defn ast-impldef [] 28)
(defn ast-private [] 29)
(defn ast-computationbuilder [] 30)
(defn ast-defmacro [] 31)
(defn ast-pat-wildcard [] 40)
(defn ast-pat-var [] 41)
(defn ast-pat-lit [] 42)
(defn ast-pat-constructor [] 43)
(defn ast-pat-recordpat [] 44)
(defn make-lit-int [value] (let [v (vector-new 2)] (vector-push (vector-push v 1) value)))
(defn make-lit-float [start end] (let [v (vector-new 3)] (vector-push (vector-push (vector-push v (ast-lit-float)) start) end)))
(defn make-lit-bool [b] (let [v (vector-new 2)] (vector-push (vector-push v 2) b)))
(defn make-var [name-hash] (let [v (vector-new 2)] (vector-push (vector-push v 4) name-hash)))
(defn make-lit-unit [] (vector-push (vector-new 1) (ast-lit-unit)))
(defn make-if [cond-expr then-expr else-expr] (let [v (vector-new 4)] (vector-push (vector-push (vector-push (vector-push v (ast-if)) cond-expr) then-expr) else-expr)))
(defn make-let [name-hash init-expr body-expr] (let [v (vector-new 4)] (vector-push (vector-push (vector-push (vector-push v (ast-let)) name-hash) init-expr) body-expr)))
(defn make-ann [expr] (let [v (vector-new 2)] (vector-push (vector-push v (ast-ann)) expr)))
(defn make-recordlit [type-name-hash] (let [v (vector-new 8)] (vector-push (vector-push (vector-push v (ast-recordlit)) type-name-hash) 0)))
(defn make-fieldaccess [expr field-name-hash] (let [v (vector-new 3)] (vector-push (vector-push (vector-push v (ast-fieldaccess)) expr) field-name-hash)))
(defn make-recordupdate [base-expr] (let [v (vector-new 8)] (vector-push (vector-push (vector-push v (ast-recordupdate)) base-expr) 0)))
(defn make-computation [builder-hash] (let [v (vector-new 8)] (vector-push (vector-push (vector-push v (ast-computation)) builder-hash) 0)))
(defn make-type-decl [name-hash] (let [v (vector-new 2)] (vector-push (vector-push v (ast-type-decl)) name-hash)))
(defn make-record-def [name-hash] (let [v (vector-new 2)] (vector-push (vector-push v (ast-recorddef)) name-hash)))
(defn make-type-alias [name-hash] (let [v (vector-new 2)] (vector-push (vector-push v (ast-typealias)) name-hash)))
(defn make-type-constrained [name-hash] (let [v (vector-new 2)] (vector-push (vector-push v (ast-typeconstrained)) name-hash)))
(defn make-module-decl [name-hash] (let [v (vector-new 8)] (vector-push (vector-push (vector-push v (ast-module-decl)) name-hash) 0)))
(defn make-import-decl [name-hash name-start name-end] (let [v (vector-new 4)] (vector-push (vector-push (vector-push (vector-push v (ast-import-decl)) name-hash) name-start) name-end)))
(defn make-trait-def [name-hash] (let [v (vector-new 8)] (vector-push (vector-push (vector-push v (ast-traitdef)) name-hash) 0)))
(defn make-impl-def [trait-name-hash type-name-hash] (let [v (vector-new 8)] (vector-push (vector-push (vector-push (vector-push v (ast-impldef)) trait-name-hash) type-name-hash) 0)))
(defn make-private [inner-node] (let [v (vector-new 2)] (vector-push (vector-push v (ast-private)) inner-node)))
(defn make-computation-builder [name-hash bind-hash return-hash] (let [v (vector-new 4)] (vector-push (vector-push (vector-push (vector-push v (ast-computationbuilder)) name-hash) bind-hash) return-hash)))
(defn make-defmacro [name-hash] (let [v (vector-new 3)] (vector-push (vector-push (vector-push v (ast-defmacro)) name-hash) 0)))
(defn make-quote [expr] (let [v (vector-new 2)] (vector-push (vector-push v (ast-quote)) expr)))
(defn make-unquote [expr] (let [v (vector-new 2)] (vector-push (vector-push v (ast-unquote)) expr)))
(defn make-unquote-splice [expr] (let [v (vector-new 2)] (vector-push (vector-push v (ast-unquote-splice)) expr)))
(defn ast-tag [node] (vector-get node 0))
(defn ast-is-leaf [tag] (if (= tag 1) 1 (if (= tag 2) 1 (if (= tag 4) 1 (if (= tag 3) 1 (if (= tag 19) 1 (if (= tag 32) 1 0)))))))
(defn recordlit-contains-var-loop [node target-hash idx count] (if (>= idx count) 0 (let [expr (vector-get node (+ 4 (* idx 2))) found (ast-contains-var expr target-hash)] (if (= found 1) 1 (recordlit-contains-var-loop node target-hash (+ idx 1) count)))))
(defn recordupdate-contains-var-loop [node target-hash idx count] (if (>= idx count) 0 (let [expr (vector-get node (+ 4 (* idx 2))) found (ast-contains-var expr target-hash)] (if (= found 1) 1 (recordupdate-contains-var-loop node target-hash (+ idx 1) count)))))
(defn computation-contains-var-loop [node target-hash idx count] (if (>= idx count) 0 (let [expr (vector-get node (+ 5 (* idx 3))) found (ast-contains-var expr target-hash)] (if (= found 1) 1 (computation-contains-var-loop node target-hash (+ idx 1) count)))))
(defn ast-contains-var [node target-hash] (let [tag (vector-get node 0)] (if (= tag 4) (if (= (vector-get node 1) target-hash) 1 0) (if (= tag 1) 0 (if (= tag 2) 0 (if (= tag 3) 0 (if (= tag 11) (ast-contains-var (vector-get node 1) target-hash) (if (= tag 12) (recordlit-contains-var-loop node target-hash 0 (vector-get node 2)) (if (= tag 13) (ast-contains-var (vector-get node 1) target-hash) (if (= tag 14) (let [base-found (ast-contains-var (vector-get node 1) target-hash)] (if (= base-found 1) 1 (recordupdate-contains-var-loop node target-hash 0 (vector-get node 2)))) (if (= tag 15) (computation-contains-var-loop node target-hash 0 (vector-get node 2)) (if (= tag 16) (ast-contains-var (vector-get node 1) target-hash) (if (= tag 17) (ast-contains-var (vector-get node 1) target-hash) (if (= tag 18) (ast-contains-var (vector-get node 1) target-hash) (if (= tag 6) (let [r1 (ast-contains-var (vector-get node 1) target-hash)] (if (= r1 1) 1 (let [r2 (ast-contains-var (vector-get node 2) target-hash)] (if (= r2 1) 1 (ast-contains-var (vector-get node 3) target-hash))))) (if (= tag 7) (let [r1 (ast-contains-var (vector-get node 2) target-hash)] (if (= r1 1) 1 (ast-contains-var (vector-get node 3) target-hash))) (if (= tag 5) (let [argc (vector-get node 2)] (if (> argc 0) (let [r1 (ast-contains-var (vector-get node 3) target-hash)] (if (= r1 1) 1 (if (> argc 1) (ast-contains-var (vector-get node 4) target-hash) 0))) 0)) 0)))))))))))))))))
(defn recordlit-count-fields-loop [node idx count] (if (>= idx count) 0 (+ (ast-count-nodes (vector-get node (+ 4 (* idx 2)))) (recordlit-count-fields-loop node (+ idx 1) count))))
(defn recordupdate-count-fields-loop [node idx count] (if (>= idx count) 0 (+ (ast-count-nodes (vector-get node (+ 4 (* idx 2)))) (recordupdate-count-fields-loop node (+ idx 1) count))))
(defn computation-count-steps-loop [node idx count] (if (>= idx count) 0 (+ (ast-count-nodes (vector-get node (+ 5 (* idx 3)))) (computation-count-steps-loop node (+ idx 1) count))))
(defn ast-count-nodes [node] (let [tag (vector-get node 0)] (if (= (ast-is-leaf tag) 1) 1 (if (= tag 11) (+ 1 (ast-count-nodes (vector-get node 1))) (if (= tag 12) (+ 1 (recordlit-count-fields-loop node 0 (vector-get node 2))) (if (= tag 13) (+ 1 (ast-count-nodes (vector-get node 1))) (if (= tag 14) (+ 1 (+ (ast-count-nodes (vector-get node 1)) (recordupdate-count-fields-loop node 0 (vector-get node 2)))) (if (= tag 15) (+ 1 (computation-count-steps-loop node 0 (vector-get node 2))) (if (= tag 16) (+ 1 (ast-count-nodes (vector-get node 1))) (if (= tag 17) (+ 1 (ast-count-nodes (vector-get node 1))) (if (= tag 18) (+ 1 (ast-count-nodes (vector-get node 1))) (if (= tag 6) (+ 1 (+ (ast-count-nodes (vector-get node 1)) (+ (ast-count-nodes (vector-get node 2)) (ast-count-nodes (vector-get node 3))))) (if (= tag 7) (+ 1 (+ (ast-count-nodes (vector-get node 2)) (ast-count-nodes (vector-get node 3)))) (if (= tag 5) (let [argc (vector-get node 2)] (if (> argc 0) (if (> argc 1) (+ 1 (+ (ast-count-nodes (vector-get node 3)) (ast-count-nodes (vector-get node 4)))) (+ 1 (ast-count-nodes (vector-get node 3)))) 1)) (if (= tag 9) (let [ec (vector-get node 1)] (if (> ec 0) (if (> ec 1) (if (> ec 2) (if (> ec 3) (if (> ec 4) (+ 1 (+ (ast-count-nodes (vector-get node 2)) (+ (ast-count-nodes (vector-get node 3)) (+ (ast-count-nodes (vector-get node 4)) (+ (ast-count-nodes (vector-get node 5)) (ast-count-nodes (vector-get node 6))))))) (+ 1 (+ (ast-count-nodes (vector-get node 2)) (+ (ast-count-nodes (vector-get node 3)) (+ (ast-count-nodes (vector-get node 4)) (ast-count-nodes (vector-get node 5))))))) (+ 1 (+ (ast-count-nodes (vector-get node 2)) (+ (ast-count-nodes (vector-get node 3)) (ast-count-nodes (vector-get node 4)))))) (+ 1 (+ (ast-count-nodes (vector-get node 2)) (ast-count-nodes (vector-get node 3))))) (+ 1 (ast-count-nodes (vector-get node 2)))) 1)) (if (= tag 10) (let [ac (vector-get node 2) sc (ast-count-nodes (vector-get node 1))] (if (> ac 0) (if (> ac 1) (if (> ac 2) (+ 1 (+ sc (+ (+ (ast-count-nodes (vector-get node 3)) (ast-count-nodes (vector-get node 4))) (+ (+ (ast-count-nodes (vector-get node 5)) (ast-count-nodes (vector-get node 6))) (+ (ast-count-nodes (vector-get node 7)) (ast-count-nodes (vector-get node 8))))))) (+ 1 (+ sc (+ (+ (ast-count-nodes (vector-get node 3)) (ast-count-nodes (vector-get node 4))) (+ (ast-count-nodes (vector-get node 5)) (ast-count-nodes (vector-get node 6))))))) (+ 1 (+ sc (+ (ast-count-nodes (vector-get node 3)) (ast-count-nodes (vector-get node 4)))))) (+ 1 sc))) 1))))))))))))))))
(defn demo-main [] (let [lit (make-lit-int 42) var1 (make-var 99) if-node (let [v (vector-new 4)] (vector-push (vector-push (vector-push (vector-push v 6) var1) lit) (make-lit-int 0))) let-node (let [v (vector-new 4)] (vector-push (vector-push (vector-push (vector-push v 7) 99) lit) if-node))] (do (print (ast-tag lit)) (print (vector-get lit 1)) (print (ast-match)) (print (ast-is-leaf 1)) (print (ast-is-leaf 6)) (print (ast-count-nodes lit)) (print (ast-count-nodes if-node)) (print (ast-contains-var if-node 99)) (print (ast-contains-var if-node 88)) (print (ast-contains-var let-node 99)) (let [do-node (vector-push (vector-push (vector-push (vector-push (vector-new 4) 9) 2) var1) (make-lit-int 0))] (print (ast-count-nodes do-node))) (let [match-node (vector-push (vector-push (vector-push (vector-push (vector-push (vector-new 6) 10) (make-lit-int 0)) 1) (make-lit-int 1)) var1)] (print (ast-count-nodes match-node))) 0)))
