[package]
name = "lsharp-tooling"
version.workspace = true
edition.workspace = true

[dependencies]
lsharp-syntax = { path = "../lsharp-syntax" }
lsharp-types = { path = "../lsharp-types" }
lsharp-ir = { path = "../lsharp-ir" }
lsharp-wasm = { path = "../lsharp-wasm" }
lsharp-lsp = { path = "../lsharp-lsp" }
miette.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
insta.workspace = true
serde_json.workspace = true
wasmtime.workspace = true
