(module App.Cli)
(import Syntax.AST)
(import Backend.Wasm.Compiler)
(import Tools.Doc.DocTools)
(import Tools.Text.Formatter)
(import Syntax.Lexer)
(import Tools.Lsp.LspServer)
(import Syntax.Parser)
(import Tools.Test.TestRunner)
(import Types.TypeInfer)
(import Types.TypeScheme)
(import Backend.Wasm.WasmEmit)
(defn exit-success [] 0)
(defn exit-compile-error [] 1)
(defn exit-runtime-error [] 2)
(defn exit-unknown-command [] 127)
(defn exit-code-success [] 0)
(defn exit-code-compile-error [] 1)
(defn exit-code-runtime-error [] 2)
(defn exit-code-unknown-command [] 127)
(defn compile-target-preview1 [] 0)
(defn compile-target-component [] 1)
(defn compile-target-invalid [] (- 0 1))
(defn default-compile-target [] (compile-target-preview1))
(defn parse-compile-target-name [target-name] (if (string-eq target-name "wasi-preview1") (compile-target-preview1) (if (or (string-eq target-name "wasi-component") (string-eq target-name "wasm")) (compile-target-component) (compile-target-invalid))))
(defn cmd-parse [] 1)
(defn cmd-check [] 2)
(defn cmd-compile [] 3)
(defn cmd-build [] 4)
(defn cmd-test [] 5)
(defn cmd-review [] 6)
(defn cmd-doc-ack [] 7)
(defn cmd-doc-check [] 8)
(defn cmd-install [] 9)
(defn cmd-repl [] 10)
(defn cmd-lsp [] 11)
(defn cmd-fmt [] 12)
(defn cmd-doc [] 13)
(defn arg-parse [cmd-name] (if (string-eq cmd-name "parse") (cmd-parse) (if (string-eq cmd-name "check") (cmd-check) (if (string-eq cmd-name "compile") (cmd-compile) (if (string-eq cmd-name "build") (cmd-build) (if (string-eq cmd-name "test") (cmd-test) (if (string-eq cmd-name "review") (cmd-review) (if (string-eq cmd-name "doc-ack") (cmd-doc-ack) (if (string-eq cmd-name "doc-check") (cmd-doc-check) (if (string-eq cmd-name "install") (cmd-install) (if (string-eq cmd-name "repl") (cmd-repl) (if (string-eq cmd-name "lsp") (cmd-lsp) (if (string-eq cmd-name "fmt") (cmd-fmt) (if (string-eq cmd-name "doc") (cmd-doc) 0))))))))))))))
(defn parse-first-decl-tag [program] (if (> (vector-length program) 0) (vector-get (vector-get program 0) 0) 0))
(defn parse-decl-tag-text [tag] (if (= tag 20) "defn" (if (= tag 25) "module" (if (= tag 26) "import" (string-concat "decl-" (int-to-string tag))))))
(defn parse-expr-tag-text [tag] (if (= tag 1) "int" (if (= tag 2) "bool" (if (= tag 3) "string" (if (= tag 4) "var" (if (= tag 5) "apply" (if (= tag 6) "if" (if (= tag 7) "let" (if (= tag 8) "fn" (if (= tag 9) "do" (if (= tag 10) "match" (if (= tag 32) "unit" (string-concat "expr-" (int-to-string tag))))))))))))))
(defn parse-first-decl-text [program] (if (> (vector-length program) 0) (parse-decl-tag-text (vector-get (vector-get program 0) 0)) "none"))
(defn parse-defn-body-index [decl] (+ 3 (vector-get decl 2)))
(defn parse-first-body-tag [program] (if (> (vector-length program) 0) (let [decl0 (vector-get program 0)] (if (= (vector-get decl0 0) 20) (vector-get (vector-get decl0 (parse-defn-body-index decl0)) 0) 0)) 0))
(defn parse-first-body-text [program] (let [tag (parse-first-body-tag program)] (if (= tag 0) "none" (parse-expr-tag-text tag))))
(defn parse-decl-count-text [program] (string-concat "decls:" (int-to-string (vector-length program))))
(defn diagnostics-summary-text [count code body] (if (= count 0) "diagnostics:0" (string-concat "diagnostics:" (string-concat (int-to-string count) (string-concat "," (string-concat code (string-concat "@1:1" (string-concat ",first-body:" body))))))))
(defn parse-diagnostic-code [diag] (vector-get diag 1))
(defn parse-diagnostics-first-code [diagnostics] (if (> (vector-length diagnostics) 0) (parse-diagnostic-code (vector-get diagnostics 0)) 0))
(defn parse-diagnostic-body-from-code [code] (if (= code 1001) "unexpected token )" (if (= code 1002) "unexpected token ]" "parse error")))
(defn parse-diagnostics-body-text [diagnostics] (if (> (vector-length diagnostics) 0) (parse-diagnostic-body-from-code (parse-diagnostics-first-code diagnostics)) ""))
(defn check-diagnostic-body-from-code [code] (if (= code (error-code-undefined)) "undefined symbol" (if (= code (error-code-if-cond)) "if condition must be Bool" (if (= code (error-code-if-branch)) "if branches must have same type" (if (= code (error-code-arg-mismatch)) "function argument type mismatch" (if (= code (error-code-infinite)) "infinite type" "type error"))))))
(defn check-diagnostics-body-text [program] (let [code (check-diagnostics-first-code program)] (if (= code 0) "" (check-diagnostic-body-from-code code))))
(defn run-parse-source [src opts] (let [program (parse-program src) diagnostics (parse-diagnostics src) diagnostics-count (vector-length diagnostics) diagnostics-text (diagnostics-summary-text diagnostics-count "P0001" (parse-diagnostics-body-text diagnostics))] (do (print-string (parse-decl-count-text program)) (print-string "
") (print-string (string-concat "first-decl:" (parse-first-decl-text program))) (print-string "
") (print-string (string-concat "first-body:" (parse-first-body-text program))) (print-string "
") (print-string diagnostics-text) (print-string "
") (exit-success))))
(defn builtin-type-name-text [type-hash] (if (= type-hash 100) "Int" (if (= type-hash 200) "Bool" (if (= type-hash 300) "String" (if (= type-hash 400) "Float" (if (= type-hash 500) "Unit" (string-concat "type-" (int-to-string type-hash))))))))
(defn render-type-text [ty] (let [tag (ty-tag ty)] (if (= tag 1) (builtin-type-name-text (ty-name ty)) (if (= tag 2) (string-concat "t" (int-to-string (ty-name ty))) (if (= tag 3) "Fn" (if (= tag 4) (string-concat "record-" (int-to-string (ty-name ty))) "Unknown"))))))
(defn run-check-source [src opts] (let [program (parse-program src) ty (infer program) rendered (render-type-text ty) diagnostics-count (check-diagnostics-count-program program) diagnostics-text (diagnostics-summary-text diagnostics-count "T0001" (check-diagnostics-body-text program))] (do (print-string rendered) (print-string "
") (print-string diagnostics-text) (print-string "
") (exit-success))))
(defn run-fmt-source [src opts] (let [program (parse-program src) formatted (format-program-with-source program src)] (do (print-string formatted) (exit-success))))
(defn wasm-size-text [size] (string-concat "wasm-size:" (int-to-string size)))
(defn run-compile-source [src opts] (let [program (parse-program src) ir (lower program) wasm-size (emit-wasm-with-target ir opts)] (do (print-string (wasm-size-text wasm-size)) (print-string "
") (exit-success))))
(defn run-compile-output [file-path output-path opts] (if (file-exists? file-path) (let [src (read-file file-path) program (parse-program src) ir (lower program) wasm-size (emit-wasm-with-target ir opts) summary (wasm-size-text wasm-size)] (do (write-file output-path summary) (print-string summary) (print-string "
") (exit-success))) (exit-compile-error)))
(defn run-build-output [file-path output-path opts] (run-compile-output file-path output-path opts))
(defn test-examples-text [count] (string-concat "examples:" (int-to-string count)))
(defn test-invariants-text [count] (string-concat "invariants:" (int-to-string count)))
(defn test-failures-text [count] (string-concat "failures:" (int-to-string count)))
(defn run-test-source [src opts] (let [suite (generate-tests-from-source src) example-results (vector-get suite 0) invariant-results (vector-get suite 1) example-count (vector-length example-results) invariant-count (vector-length invariant-results) failed (+ (count-failed-results example-results) (count-failed-results invariant-results))] (do (print-string (test-examples-text example-count)) (print-string "
") (print-string (test-invariants-text invariant-count)) (print-string "
") (print-string (test-failures-text failed)) (print-string "
") (if (> failed 0) (exit-runtime-error) (exit-success)))))
(defn run-review-source [src opts] (let [program (parse-program src) review (generate-review program opts) diagnostics (vector-get review 1) review-title (review-summary-title diagnostics) review-body (review-summary-body diagnostics) review-severity (review-summary-severity diagnostics) review-code-location (review-summary-code-location diagnostics)] (do (print (vector-length diagnostics)) (print-string review-title) (print-string "
") (print-string review-body) (print-string "
") (print-string review-severity) (print-string "
") (print-string review-code-location) (print-string "
") (exit-success))))
(defn run-doc-source [src opts] (let [program (parse-program src) doc (generate program opts) title (vector-get doc 0) body (vector-get doc 1)] (do (print-string title) (print-string "
") (print-string body) (print-string "
") (exit-success))))
(defn run-parse [file-path opts] (if (file-exists? file-path) (run-parse-source (read-file file-path) opts) (exit-compile-error)))
(defn run-check [file-path opts] (if (file-exists? file-path) (run-check-source (read-file file-path) opts) (exit-compile-error)))
(defn run-compile [file-path opts] (if (file-exists? file-path) (run-compile-source (read-file file-path) opts) (exit-compile-error)))
(defn run-build [file-path opts] (if (file-exists? file-path) (run-compile file-path opts) (exit-compile-error)))
(defn run-test [file-path opts] (if (file-exists? file-path) (run-test-source (read-file file-path) opts) (exit-compile-error)))
(defn run-review [file-path opts] (if (file-exists? file-path) (run-review-source (read-file file-path) opts) (exit-compile-error)))
(defn print-doc-trailers-loop [trailers idx count] (if (>= idx count) 0 (do (print-string (vector-get trailers idx)) (print-string "
") (print-doc-trailers-loop trailers (+ idx 1) count))))
(defn print-doc-payload [payload] (let [trailers (vector-get payload 3)] (do (print-string (vector-get payload 0)) (print-string "
") (print-string (vector-get payload 1)) (print-string "
") (print-string (vector-get payload 2)) (print-string "
") (print-doc-trailers-loop trailers 0 (vector-length trailers)))))
(defn run-doc-ack [file-path opts] (if (file-exists? file-path) (let [src (read-file file-path) program (parse-program src) ack (generate-doc-ack program "anonymous")] (do (print-doc-payload ack) (exit-success))) (exit-compile-error)))
(defn run-doc-check [file-path opts] (if (file-exists? file-path) (let [src (read-file file-path) program (parse-program src) check (generate-doc-check program "anonymous")] (do (print-doc-payload check) (exit-success))) (exit-compile-error)))
(defn install-plan-title [package] (string-concat "package:" package))
(defn install-plan-body [package] "status:planned")
(defn run-install [package opts] (if (> (string-length package) 0) (do (print-string (install-plan-title package)) (print-string "
") (print-string (install-plan-body package)) (print-string "
") (exit-success)) (exit-compile-error)))
(defn repl-session-new [] (let [v (vector-new 3)] (vector-push (vector-push (vector-push v (ref-new 0)) (ref-new 0)) (ref-new 0))))
(defn repl-session-eval-count [session] (ref-get (vector-get session 0)))
(defn repl-session-last-type-name [session] (ref-get (vector-get session 1)))
(defn repl-session-total-input-bytes [session] (ref-get (vector-get session 2)))
(defn repl-session-eval [session src] (let [program (parse-program src) ty (infer program) type-name (ty-name ty)] (do (ref-set (vector-get session 0) (+ (repl-session-eval-count session) 1)) (ref-set (vector-get session 1) type-name) (ref-set (vector-get session 2) (+ (repl-session-total-input-bytes session) (string-length src))) type-name)))
(defn repl-session-run-loop [session inputs idx count] (if (>= idx count) 0 (do (repl-session-eval session (vector-get inputs idx)) (repl-session-run-loop session inputs (+ idx 1) count))))
(defn repl-session-run [inputs] (let [session (repl-session-new) _ (repl-session-run-loop session inputs 0 (vector-length inputs)) summary (vector-new 3)] (vector-push (vector-push (vector-push summary (repl-session-eval-count session)) (repl-session-total-input-bytes session)) (repl-session-last-type-name session))))
(defn repl-summary-type-text [summary] (string-concat "type:" (builtin-type-name-text (vector-get summary 2))))
(defn repl-summary-evals-text [summary] (string-concat "evals:" (int-to-string (vector-get summary 0))))
(defn repl-summary-input-bytes-text [summary] (string-concat "input-bytes:" (int-to-string (vector-get summary 1))))
(defn repl-warmup-summary [] (let [inputs (vector-push (vector-new 1) "(defn main [] 42)")] (repl-session-run inputs)))
(defn repl-warmup-type-name [] (let [summary (repl-warmup-summary)] (vector-get summary 2)))
(defn repl-warmup-type-text [] (builtin-type-name-text (repl-warmup-type-name)))
(defn run-repl [opts] (let [summary (repl-warmup-summary)] (do (print-string (repl-summary-type-text summary)) (print-string "
") (print-string (repl-summary-evals-text summary)) (print-string "
") (print-string (repl-summary-input-bytes-text summary)) (print-string "
") (exit-success))))
(defn lsp-bool-text [value] (if (= value 1) "true" "false"))
(defn lsp-sync-kind-text [kind] (if (= kind 1) "full" (string-concat "sync-" (int-to-string kind))))
(defn lsp-loop-request [method-id params] (let [v (vector-new 2)] (vector-push (vector-push v method-id) params)))
(defn lsp-init-summary [] (let [requests (vector-push (vector-new 1) (lsp-loop-request (lsp-method-initialize) 0)) summary (server-loop-sequence requests)] summary))
(defn lsp-init-capabilities [summary] (let [results (vector-get summary 0)] (vector-get results 0)))
(defn lsp-summary-requests-text [summary] (string-concat "requests:" (int-to-string (vector-get summary 2))))
(defn lsp-summary-documents-text [summary] (string-concat "documents:" (int-to-string (vector-get summary 1))))
(defn lsp-summary-source-bytes-text [summary] (string-concat "source-bytes:" (int-to-string (vector-get summary 3))))
(defn lsp-transport-request-id [request] (vector-get request 1))
(defn lsp-transport-method-id [request] (vector-get request 2))
(defn lsp-transport-params [request] (vector-get request 3))
(defn lsp-transport-uri [request] (if (> (vector-length (lsp-transport-params request)) 0) (vector-get (lsp-transport-params request) 0) 0))
(defn lsp-transport-method-not-found-code [] (- 0 32601))
(defn lsp-transport-dispatch-request [state request] (let [request-id (lsp-transport-request-id request) method-id (lsp-transport-method-id request) params (lsp-transport-params request) uri (lsp-transport-uri request) result (json-rpc-dispatch method-id params state)] (if (= method-id (lsp-method-initialize)) (lsp-render-initialize-frame request-id) (if (= method-id (lsp-method-shutdown)) (lsp-render-shutdown-frame request-id) (if (= method-id (lsp-method-did-open)) (lsp-render-didopen-frame uri (server-state-source-length state)) (if (= method-id (lsp-method-did-change)) (lsp-render-didchange-frame uri (server-state-source-length state)) (if (= method-id (lsp-method-goto-def)) (lsp-render-location-frame request-id result) (if (= method-id (lsp-method-hover)) (lsp-render-hover-frame request-id result) (if (= method-id (lsp-method-references)) (lsp-render-locations-frame request-id result) (if (= method-id (lsp-method-completion)) (lsp-render-completion-frame request-id result) (if (= method-id (lsp-method-formatting)) (lsp-render-formatting-frame request-id result) (if (= method-id (lsp-method-rename)) (lsp-render-rename-frame request-id result) (lsp-render-error-frame request-id (lsp-transport-method-not-found-code) "Method not found")))))))))))))
(defn run-lsp-transport-request [request] (let [state (server-state-new)] (lsp-transport-dispatch-request state request)))
(defn lsp-transport-sequence-loop [state requests idx count frames] (if (>= idx count) frames (lsp-transport-sequence-loop state requests (+ idx 1) count (vector-push frames (lsp-transport-dispatch-request state (vector-get requests idx))))))
(defn run-lsp-transport-sequence [requests] (let [state (server-state-new) frames (lsp-transport-sequence-loop state requests 0 (vector-length requests) (vector-new 8)) summary (vector-new 4)] (vector-push (vector-push (vector-push (vector-push summary frames) (server-state-doc-count state)) (server-state-request-count state)) (server-state-source-length state))))
(defn lsp-stdio-frame-header [frame] (vector-get frame 0))
(defn lsp-stdio-frame-message [frame] (vector-get frame 1))
(defn lsp-stdio-frame-content-length [frame] (lsp-parse-content-length (lsp-stdio-frame-header frame)))
(defn lsp-stdio-message-request [msg] (let [parsed (parse-json-rpc-request msg) request-id (vector-get msg 1) method-id (vector-get parsed 0) params (vector-get parsed 1)] (vector-push (vector-push (vector-push (vector-push (vector-new 4) 2) request-id) method-id) params)))
(defn lsp-stdio-dispatch-frame [state frame] (let [request (lsp-stdio-message-request (lsp-stdio-frame-message frame)) rendered (lsp-transport-dispatch-request state request) content-length (lsp-stdio-frame-content-length frame)] (vector-push (vector-push (vector-new 2) rendered) content-length)))
(defn run-lsp-stdio-frame [frame] (let [state (server-state-new)] (lsp-stdio-dispatch-frame state frame)))
(defn lsp-stdio-sequence-loop [state frames idx count rendered last-content-length] (if (>= idx count) (vector-push (vector-push (vector-new 2) rendered) last-content-length) (let [result (lsp-stdio-dispatch-frame state (vector-get frames idx))] (lsp-stdio-sequence-loop state frames (+ idx 1) count (vector-push rendered (vector-get result 0)) (vector-get result 1)))))
(defn run-lsp-stdio-sequence [frames] (let [state (server-state-new) result (lsp-stdio-sequence-loop state frames 0 (vector-length frames) (vector-new 8) 0) rendered (vector-get result 0) last-content-length (vector-get result 1) summary (vector-new 4)] (vector-push (vector-push (vector-push (vector-push summary rendered) (server-state-request-count state)) (server-state-source-length state)) last-content-length)))
(defn lsp-stdio-find-header-end-loop [src idx len] (if (> (+ idx 3) len) len (if (= (string-char-at src idx) 13) (if (= (string-char-at src (+ idx 1)) 10) (if (= (string-char-at src (+ idx 2)) 13) (if (= (string-char-at src (+ idx 3)) 10) idx (lsp-stdio-find-header-end-loop src (+ idx 1) len)) (lsp-stdio-find-header-end-loop src (+ idx 1) len)) (lsp-stdio-find-header-end-loop src (+ idx 1) len)) (lsp-stdio-find-header-end-loop src (+ idx 1) len))))
(defn lsp-stdio-find-pattern-loop [src pattern idx len] (if (>= idx len) (- 0 1) (if (lsp-match-at src idx pattern) idx (lsp-stdio-find-pattern-loop src pattern (+ idx 1) len))))
(defn lsp-stdio-is-digit [c] (if (< c 48) false (if (> c 57) false true)))
(defn lsp-stdio-parse-int-loop [src idx len acc started] (if (>= idx len) acc (let [c (string-char-at src idx)] (if (lsp-stdio-is-digit c) (lsp-stdio-parse-int-loop src (+ idx 1) len (+ (- c 48) (* acc 10)) 1) (if (= started 1) acc (lsp-stdio-parse-int-loop src (+ idx 1) len acc 0))))))
(defn lsp-stdio-body-id [body] (let [id-pos (lsp-stdio-find-pattern-loop body "\"id\":" 0 (string-length body))] (if (< id-pos 0) 0 (lsp-stdio-parse-int-loop body (+ id-pos 5) (string-length body) 0 0))))
(defn lsp-stdio-body-method [body] (if (>= (lsp-stdio-find-pattern-loop body "\"method\":\"initialize\"" 0 (string-length body)) 0) (lsp-method-initialize) (if (>= (lsp-stdio-find-pattern-loop body "\"method\":\"shutdown\"" 0 (string-length body)) 0) (lsp-method-shutdown) 999)))
(defn lsp-stdio-body-message [body] (vector-push (vector-push (vector-push (vector-push (vector-new 4) 2) (lsp-stdio-body-id body)) (lsp-stdio-body-method body)) 0))
(defn lsp-stdio-wire-loop [state wire idx len out] (if (>= idx len) out (let [header-end (lsp-stdio-find-header-end-loop wire idx len) header (substring wire idx header-end) content-length (lsp-parse-content-length header) body-start (+ header-end 4) body-end (+ body-start content-length) body (substring wire body-start body-end) rendered (lsp-transport-dispatch-request state (lsp-stdio-message-request (lsp-stdio-body-message body)))] (lsp-stdio-wire-loop state wire body-end len (string-concat out rendered)))))
(defn run-lsp-stdio-wire [wire] (let [state (server-state-new)] (lsp-stdio-wire-loop state wire 0 (string-length wire) "")))
(defn run-lsp-stdio-server [] (let [wire (read-stdin)] (do (print-string (run-lsp-stdio-wire wire)) (exit-success))))
(defn run-lsp [opts] (let [summary (lsp-init-summary) caps (lsp-init-capabilities summary)] (do (print-string (string-concat "sync:" (lsp-sync-kind-text (vector-get caps 0)))) (print-string "
") (print-string (string-concat "hover:" (lsp-bool-text (vector-get caps 1)))) (print-string "
") (print-string (string-concat "completion:" (lsp-bool-text (vector-get caps 2)))) (print-string "
") (print-string (string-concat "definition:" (lsp-bool-text (vector-get caps 3)))) (print-string "
") (print-string (string-concat "references:" (lsp-bool-text (vector-get caps 4)))) (print-string "
") (print-string (string-concat "rename:" (lsp-bool-text (vector-get caps 5)))) (print-string "
") (print-string (string-concat "formatting:" (lsp-bool-text (vector-get caps 6)))) (print-string "
") (print-string (lsp-summary-requests-text summary)) (print-string "
") (print-string (lsp-summary-documents-text summary)) (print-string "
") (print-string (lsp-summary-source-bytes-text summary)) (print-string "
") (exit-success))))
(defn run-fmt [file-path opts] (if (file-exists? file-path) (run-fmt-source (read-file file-path) opts) (exit-compile-error)))
(defn run-doc [file-path opts] (if (file-exists? file-path) (run-doc-source (read-file file-path) opts) (exit-compile-error)))
(defn parse-diagnostics-loop [spans pos-ref src diagnostics] (if (== (p-current spans pos-ref) 99) diagnostics (let [before (ref-get pos-ref) parsed (parse-with-recovery spans pos-ref src diagnostics) next-diagnostics (vector-get parsed 1)] (if (= (ref-get pos-ref) before) (do (p-advance pos-ref) (parse-diagnostics-loop spans pos-ref src next-diagnostics)) (parse-diagnostics-loop spans pos-ref src next-diagnostics)))))
(defn parse-diagnostics [src] (let [spans (tokenize-with-spans src) pos-ref (ref-new 0) diagnostics (parse-diagnostics-loop spans pos-ref src (collect-diagnostics))] diagnostics))
(defn parse-diagnostics-count [src] (let [diagnostics (parse-diagnostics src)] (vector-length diagnostics)))
(defn check-diagnostics-loop [program idx len env counter count] (if (>= idx len) count (let [decl (vector-get program idx) tag (vector-get decl 0)] (if (= tag 20) (let [out (infer-defn decl env counter)] (if (= (result-failed out) 1) (check-diagnostics-loop program (+ idx 1) len env counter (+ count 1)) (let [next-env (if (> (vector-length out) 3) (vector-get out 3) env)] (check-diagnostics-loop program (+ idx 1) len next-env counter count)))) (check-diagnostics-loop program (+ idx 1) len env counter count)))))
(defn check-diagnostics-first-code-loop [program idx len env counter] (if (>= idx len) 0 (let [decl (vector-get program idx) tag (vector-get decl 0)] (if (= tag 20) (let [out (infer-defn decl env counter)] (if (= (result-failed out) 1) (result-error-code out) (let [next-env (if (> (vector-length out) 3) (vector-get out 3) env)] (check-diagnostics-first-code-loop program (+ idx 1) len next-env counter)))) (check-diagnostics-first-code-loop program (+ idx 1) len env counter)))))
(defn check-diagnostics-count-program [program] (let [counter (make-var-counter) env (init-builtin-env counter)] (check-diagnostics-loop program 0 (vector-length program) env counter 0)))
(defn check-diagnostics-first-code [program] (let [counter (make-var-counter) env (init-builtin-env counter)] (check-diagnostics-first-code-loop program 0 (vector-length program) env counter)))
(defn check-diagnostics-count [src] (let [program (parse-program src)] (check-diagnostics-count-program program)))
(defn dispatch-command-tail [cmd-id file-path opts] (if (= cmd-id (cmd-doc-ack)) (run-doc-ack file-path opts) (if (= cmd-id (cmd-doc-check)) (run-doc-check file-path opts) (if (= cmd-id (cmd-install)) (run-install file-path opts) (if (= cmd-id (cmd-repl)) (run-repl opts) (if (= cmd-id (cmd-lsp)) (run-lsp opts) (if (= cmd-id (cmd-fmt)) (run-fmt file-path opts) (if (= cmd-id (cmd-doc)) (run-doc file-path opts) (exit-unknown-command)))))))))
(defn dispatch-command [cmd-id file-path opts] (if (= cmd-id (cmd-parse)) (run-parse file-path opts) (if (= cmd-id (cmd-check)) (run-check file-path opts) (if (= cmd-id (cmd-compile)) (run-compile file-path opts) (if (= cmd-id (cmd-build)) (run-build file-path opts) (if (= cmd-id (cmd-test)) (run-test file-path opts) (if (= cmd-id (cmd-review)) (run-review file-path opts) (dispatch-command-tail cmd-id file-path opts))))))))
(defn help-text [] "Usage: lsharp <command> [options] Commands: parse check compile build test review doc-ack doc-check install repl lsp fmt doc")
(defn version-text [] "lsharp 0.1.0")
(defn show-help [] (do (print-string (help-text)) (exit-success)))
(defn show-version [] (do (print-string (version-text)) (exit-success)))
(defn cli-stdout [msg] (do (print-string msg) (print-string "
") 0))
(defn cli-stderr [msg] (do (print-string (string-concat "error: " msg)) (print-string "
") 0))
(defn format-subcommand-help [cmd] (if (string-eq cmd "parse") "parse <file> - Parse source and show AST" (if (string-eq cmd "check") "check <file> - Type-check source" (if (string-eq cmd "compile") "compile <file> [-o <file>] [--target <wasi-preview1|wasi-component|wasm>] - Compile to Wasm" (if (string-eq cmd "build") "build <file> [--output <file>] [--target <wasi-preview1|wasi-component|wasm>] - Build project" (if (string-eq cmd "test") "test <file> - Run metadata tests" (if (string-eq cmd "review") "review <file> - Code review" (if (string-eq cmd "doc-ack") "doc-ack <file> - Acknowledge docs" (if (string-eq cmd "doc-check") "doc-check <file> - Check doc consistency" (if (string-eq cmd "install") "install <pkg> - Install package" (if (string-eq cmd "repl") "repl - Interactive REPL" (if (string-eq cmd "lsp") "lsp [--stdio] - Start LSP server" (if (string-eq cmd "fmt") "fmt <file> - Format source" (if (string-eq cmd "doc") "doc <file> - Generate docs" "unknown command"))))))))))))))
(defn run-command [cmd-name file-path opts] (if (or (string-eq cmd-name "--help") (string-eq cmd-name "-h")) (show-help) (if (or (string-eq cmd-name "--version") (string-eq cmd-name "-v")) (show-version) (if (string-eq cmd-name "help") (do (cli-stdout (format-subcommand-help file-path)) (exit-success)) (if (or (string-eq file-path "--help") (string-eq file-path "-h")) (do (cli-stdout (format-subcommand-help cmd-name)) (exit-success)) (let [cmd-id (arg-parse cmd-name)] (if (= cmd-id 0) (do (cli-stderr (string-concat "unknown command: " cmd-name)) (exit-code-unknown-command)) (dispatch-command cmd-id file-path opts))))))))
(defn main-dispatch [cmd-name file-path opts] (run-command cmd-name file-path opts))
(defn compile-or-build-command [cmd-name] (or (string-eq cmd-name "compile") (string-eq cmd-name "build")))
(defn output-option-flag [arg] (or (string-eq arg "-o") (string-eq arg "--output")))
(defn target-option-flag [arg] (string-eq arg "--target"))
(defn cli-option-status-ok [] 0)
(defn cli-option-status-invalid-target [] 1)
(defn cli-option-status-missing-value [] 2)
(defn cli-option-status-unsupported-option [] 3)
(defn cli-option-result [status target output-path detail] (let [result (vector-new 4)] (vector-push (vector-push (vector-push (vector-push result status) target) output-path) detail)))
(defn cli-option-result-status [result] (vector-get result 0))
(defn cli-option-result-target [result] (vector-get result 1))
(defn cli-option-result-output-path [result] (vector-get result 2))
(defn cli-option-result-detail [result] (vector-get result 3))
(defn parse-cli-options-loop [idx argc target output-path] (if (>= idx argc) (cli-option-result (cli-option-status-ok) target output-path "") (let [flag (command-line-arg idx)] (if (>= (+ idx 1) argc) (cli-option-result (cli-option-status-missing-value) target output-path flag) (let [flag-value (command-line-arg (+ idx 1))] (if (output-option-flag flag) (parse-cli-options-loop (+ idx 2) argc target flag-value) (if (target-option-flag flag) (let [parsed-target (parse-compile-target-name flag-value)] (if (< parsed-target 0) (cli-option-result (cli-option-status-invalid-target) target output-path flag-value) (parse-cli-options-loop (+ idx 2) argc parsed-target output-path))) (cli-option-result (cli-option-status-unsupported-option) target output-path flag))))))))
(defn parse-cli-options [argc] (parse-cli-options-loop 2 argc (default-compile-target) ""))
(defn cli-option-error-message [result] (let [status (cli-option-result-status result) detail (cli-option-result-detail result)] (if (= status (cli-option-status-invalid-target)) (string-concat "unsupported target: " detail) (if (= status (cli-option-status-missing-value)) (string-concat "missing value for option: " detail) (string-concat "unsupported option: " detail)))))
(defn run-command-with-cli-options [cmd-name file-path result] (let [target (cli-option-result-target result) output-path (cli-option-result-output-path result)] (if (> (string-length output-path) 0) (if (string-eq cmd-name "compile") (run-compile-output file-path output-path target) (if (string-eq cmd-name "build") (run-build-output file-path output-path target) (run-command cmd-name file-path target))) (run-command cmd-name file-path target))))
(defn main [] (let [argc (command-line-args)] (if (= argc 0) (show-help) (let [cmd-name (command-line-arg 0) file-path (if (> argc 1) (command-line-arg 1) "")] (if (and (string-eq cmd-name "lsp") (string-eq file-path "--stdio")) (run-lsp-stdio-server) (if (and (compile-or-build-command cmd-name) (> argc 2)) (let [options (parse-cli-options argc)] (if (= (cli-option-result-status options) (cli-option-status-ok)) (run-command-with-cli-options cmd-name file-path options) (do (cli-stderr (cli-option-error-message options)) (exit-code-compile-error)))) (run-command cmd-name file-path (default-compile-target))))))))
