(module App.EmbeddedCli)
(import App.CompilerMode)
(import Backend.Wasm.Compiler)
(import Syntax.Lexer)
(import Syntax.Parser)
(import Tools.Doc.DocJson)
(import Tools.Doc.DocTools)
(import Tools.Test.TestRunner)
(import Types.TypeInfer)
(import Types.TypeInferCore)
(import Types.TypeScheme)

(defn exit-success [] 0)
(defn exit-compile-error [] 1)
(defn cmd-parse [] 1)
(defn cmd-check [] 2)
(defn cmd-compile [] 3)
(defn cmd-build [] 4)
(defn cmd-test [] 5)
(defn cmd-review [] 6)
(defn cmd-doc-ack [] 7)
(defn cmd-doc-check [] 8)
(defn cmd-fmt [] 9)
(defn compile-target-preview1 [] 0)
(defn compile-target-component [] 1)
(defn compile-target-invalid [] (- 0 1))
(defn default-compile-target [] (compile-target-component))
(defn parse-compile-target-name [target-name] (if (string-eq target-name "wasi-preview1") (compile-target-preview1) (if (or (string-eq target-name "wasi-component") (string-eq target-name "wasm")) (compile-target-component) (compile-target-invalid))))
(defn arg-parse [cmd-name]
  (if (string-eq cmd-name "parse")
    (cmd-parse)
    (if (string-eq cmd-name "check")
      (cmd-check)
      (if (string-eq cmd-name "compile")
        (cmd-compile)
        (if (string-eq cmd-name "build")
          (cmd-build)
          (if (string-eq cmd-name "test")
            (cmd-test)
            (if (string-eq cmd-name "review")
              (cmd-review)
              (if (string-eq cmd-name "doc-ack")
                (cmd-doc-ack)
                (if (string-eq cmd-name "doc-check")
                  (cmd-doc-check)
                  (if (string-eq cmd-name "fmt")
                    (cmd-fmt)
                    0))))))))))
(defn parse-first-decl-tag [program] (if (> (vector-length program) 0) (vector-get (vector-get program 0) 0) 0))
(defn parse-decl-tag-text [tag] (if (= tag 20) "defn" (if (= tag 25) "module" (if (= tag 26) "import" (string-concat "decl-" (int-to-string tag))))))
(defn parse-expr-tag-text [tag] (if (= tag 1) "int" (if (= tag 2) "bool" (if (= tag 3) "string" (if (= tag 4) "var" (if (= tag 5) "apply" (if (= tag 6) "if" (if (= tag 7) "let" (if (= tag 8) "fn" (if (= tag 9) "do" (if (= tag 10) "match" (if (= tag 32) "unit" (string-concat "expr-" (int-to-string tag))))))))))))))
(defn parse-first-decl-text [program] (if (> (vector-length program) 0) (parse-decl-tag-text (vector-get (vector-get program 0) 0)) "none"))
(defn parse-defn-body-index [decl] (+ 3 (vector-get decl 2)))
(defn parse-first-body-tag [program] (if (> (vector-length program) 0) (let [decl0 (vector-get program 0)] (if (= (vector-get decl0 0) 20) (vector-get (vector-get decl0 (parse-defn-body-index decl0)) 0) 0)) 0))
(defn parse-first-body-text [program] (let [tag (parse-first-body-tag program)] (if (= tag 0) "none" (parse-expr-tag-text tag))))
(defn parse-decl-count-text [program] (string-concat "decls:" (int-to-string (vector-length program))))
(defn diagnostics-summary-text [count code body] (if (= count 0) "diagnostics:0" (string-concat "diagnostics:" (string-concat (int-to-string count) (string-concat "," (string-concat code (string-concat "@1:1" (string-concat ",first-body:" body))))))))
(defn parse-diagnostic-code [diag] (vector-get diag 1))
(defn parse-diagnostics-first-code [diagnostics] (if (> (vector-length diagnostics) 0) (parse-diagnostic-code (vector-get diagnostics 0)) 0))
(defn parse-diagnostic-body-from-code [code] (if (= code 1001) "unexpected token )" (if (= code 1002) "unexpected token ]" "parse error")))
(defn parse-diagnostics-body-text [diagnostics] (if (> (vector-length diagnostics) 0) (parse-diagnostic-body-from-code (parse-diagnostics-first-code diagnostics)) ""))
(defn check-diagnostic-body-from-code [code] (if (= code (error-code-undefined)) "undefined symbol" (if (= code (error-code-if-cond)) "if condition must be Bool" (if (= code (error-code-if-branch)) "if branches must have same type" (if (= code (error-code-arg-mismatch)) "function argument type mismatch" (if (= code (error-code-infinite)) "infinite type" "type error"))))))
(defn check-diagnostics-body-text [program] (let [code (check-diagnostics-first-code program)] (if (= code 0) "" (check-diagnostic-body-from-code code))))
(defn parse-diagnostics-loop [spans pos-ref src diagnostics] (if (== (p-current spans pos-ref) 99) diagnostics (let [before (ref-get pos-ref) parsed (parse-with-recovery spans pos-ref src diagnostics) next-diagnostics (vector-get parsed 1)] (if (= (ref-get pos-ref) before) (do (p-advance pos-ref) (parse-diagnostics-loop spans pos-ref src next-diagnostics)) (parse-diagnostics-loop spans pos-ref src next-diagnostics)))))
(defn parse-diagnostics [src] (let [spans (tokenize-with-spans src) pos-ref (ref-new 0) diagnostics (parse-diagnostics-loop spans pos-ref src (collect-diagnostics))] diagnostics))
(defn check-diagnostics-count-program [program] (infer-program-analysis-diagnostic-count (infer-program-analysis program)))
(defn check-diagnostics-first-code [program] (infer-program-analysis-first-error-code (infer-program-analysis program)))
(defn builtin-type-name-text [type-hash] (if (= type-hash 100) "Int" (if (= type-hash 200) "Bool" (if (= type-hash 300) "String" (if (= type-hash 400) "Float" (if (= type-hash 500) "Unit" (string-concat "type-" (int-to-string type-hash))))))))
(defn render-type-text [ty] (let [tag (ty-tag ty)] (if (= tag 1) (builtin-type-name-text (ty-name ty)) (if (= tag 2) (string-concat "t" (int-to-string (ty-name ty))) (if (= tag 3) "Fn" (if (= tag 4) (string-concat "record-" (int-to-string (ty-name ty))) "Unknown"))))))
(defn run-parse-source [src opts] (let [program (parse-program src) diagnostics (parse-diagnostics src) diagnostics-count (vector-length diagnostics) diagnostics-text (diagnostics-summary-text diagnostics-count "P0001" (parse-diagnostics-body-text diagnostics))] (do (print-string (parse-decl-count-text program)) (print-string "\n") (print-string (string-concat "first-decl:" (parse-first-decl-text program))) (print-string "\n") (print-string (string-concat "first-body:" (parse-first-body-text program))) (print-string "\n") (print-string diagnostics-text) (print-string "\n") (exit-success))))
(defn run-check-source [src opts] (let [program (parse-program src) analysis (infer-program-analysis program) ty (infer-program-analysis-type analysis) rendered (render-type-text ty) diagnostics-count (infer-program-analysis-diagnostic-count analysis) first-error-code (infer-program-analysis-first-error-code analysis) diagnostics-text (diagnostics-summary-text diagnostics-count "T0001" (if (= first-error-code 0) "" (check-diagnostic-body-from-code first-error-code)))] (do (print-string rendered) (print-string "\n") (print-string diagnostics-text) (print-string "\n") (exit-success))))
(defn test-examples-text [count] (string-concat "examples:" (int-to-string count)))
(defn test-invariants-text [count] (string-concat "invariants:" (int-to-string count)))
(defn test-failures-text [count] (string-concat "failures:" (int-to-string count)))
(defn run-test-source [src opts] (let [suite (generate-tests-from-source src) example-results (vector-get suite 0) invariant-results (vector-get suite 1) example-count (vector-length example-results) invariant-count (vector-length invariant-results) failed (+ (count-failed-results example-results) (count-failed-results invariant-results))] (do (print-string (test-examples-text example-count)) (print-string "\n") (print-string (test-invariants-text invariant-count)) (print-string "\n") (print-string (test-failures-text failed)) (print-string "\n") (if (> failed 0) 2 (exit-success)))))
(defn review-option-json [] 2)
(defn review-json-source-id [] 200)
(defn run-review-source [src opts] (let [program (parse-program src)] (if (= opts (review-option-json)) (let [review-json (generate-review-schema-json program (review-json-source-id))] (do (print-string review-json) (print-string "\n") (exit-success))) (let [review (generate-review program opts) diagnostics (vector-get review 1) review-title (review-summary-title diagnostics) review-body (review-summary-body diagnostics) review-severity (review-summary-severity diagnostics) review-code-location (review-summary-code-location diagnostics)] (do (print (vector-length diagnostics)) (print-string review-title) (print-string "\n") (print-string review-body) (print-string "\n") (print-string review-severity) (print-string "\n") (print-string review-code-location) (print-string "\n") (exit-success))))))
(defn print-doc-trailers-loop [trailers idx count] (if (>= idx count) 0 (do (print-string (vector-get trailers idx)) (print-string "\n") (print-doc-trailers-loop trailers (+ idx 1) count))))
(defn print-doc-payload [payload] (let [trailers (vector-get payload 3)] (do (print-string (vector-get payload 0)) (print-string "\n") (print-string (vector-get payload 1)) (print-string "\n") (print-string (vector-get payload 2)) (print-string "\n") (print-doc-trailers-loop trailers 0 (vector-length trailers)))))
(defn print-doc-trailer-only [payload] (let [trailers (vector-get payload 3)] (print-doc-trailers-loop trailers 0 (vector-length trailers))))
(defn doc-option-trailer-only [] 10)
(defn doc-option-strict-check [] 11)
(defn invalid-doc-trailer-message [] "invalid doc trailer: expected trailing comment lines")
(defn cli-stderr [msg] (do (print-string (string-concat "error: " msg)) (print-string "\n")))
(defn run-doc-ack-source [src opts] (let [program (parse-program src) ack (generate-doc-ack program "anonymous")] (do (if (= opts (doc-option-trailer-only)) (print-doc-trailer-only ack) (print-doc-payload ack)) (exit-success))))
(defn run-doc-check-source [src opts] (if (and (= opts (doc-option-strict-check)) (= (doc-check-trailer-valid? src) 0)) (do (cli-stderr (invalid-doc-trailer-message)) (exit-compile-error)) (let [program (parse-program src) check (generate-doc-check program "anonymous")] (do (print-doc-payload check) (exit-success)))))
(defn run-fmt-source [src opts] (do (print-string src) (exit-success)))
(defn wasm-size-text [size] (string-concat "wasm-size:" (int-to-string size)))
(defn component-output-boundary-message [] "wasi-component output requires external component packaging")
(defn is-path-sep [path idx] (let [ch (string-char-at path idx)] (if (= ch 47) true (if (= ch 92) true false))))
(defn find-last-path-sep [path idx len last] (if (>= idx len) last (find-last-path-sep path (+ idx 1) len (if (is-path-sep path idx) idx last))))
(defn find-last-char-loop [text idx len char-code last] (if (>= idx len) last (find-last-char-loop text (+ idx 1) len char-code (if (= (string-char-at text idx) char-code) idx last))))
(defn replace-extension [path new-ext] (let [len (string-length path) last-sep (find-last-path-sep path 0 len -1) last-dot (find-last-char-loop path 0 len 46 -1)] (if (> last-dot last-sep) (string-concat (substring path 0 last-dot) new-ext) (string-concat path new-ext))))
(defn default-output-extension [target] (if (= target (compile-target-preview1)) ".wasm" ".component.wasm"))
(defn default-output-path [file-path target] (replace-extension file-path (default-output-extension target)))
(defn compile-file-functions-data-with-cache [file-path cache-ref parse-count-ref] (compile-file-functions-payload-with-cache file-path 12 cache-ref parse-count-ref))
(defn compile-file-functions-data [file-path] (let [cache-ref (ref-new (map-new)) parse-count-ref (ref-new 0)] (compile-file-functions-data-with-cache file-path cache-ref parse-count-ref)))
(defn standalone-preview1-capability-boundary-message [] "unsupported standalone Preview1 runtime capability")
(defn compile-file-wasm-bytes [file-path] (let [pair (compile-file-functions-data file-path) functions (vector-get pair 0) data (vector-get pair 1) unsupported-opcode (standalone-preview1-first-unsupported-opcode functions)] (if (>= unsupported-opcode 0) (vector-new 0) (build-wasm-bytes-wasi-standalone functions data))))
(defn compile-source-wasm-bytes [src] (let [program (parse-program src) pair (compile-program-functions-with-source-base src program 12) functions (vector-get pair 1) data (vector-get pair 2) unsupported-opcode (standalone-preview1-first-unsupported-opcode functions)] (if (>= unsupported-opcode 0) (vector-new 0) (build-wasm-bytes-wasi-standalone functions data))))
(defn run-compile-source [src opts] (let [wasm-bytes (compile-source-wasm-bytes src) wasm-size (vector-length wasm-bytes)] (if (= wasm-size 0) (do (cli-stderr (standalone-preview1-capability-boundary-message)) (exit-compile-error)) (do (print-string (wasm-size-text wasm-size)) (print-string "\n") (exit-success)))))
(defn run-compile-output [file-path output-path opts] (if (file-exists? file-path) (if (= opts (compile-target-preview1)) (let [wasm-bytes (compile-file-wasm-bytes file-path) wasm-size (vector-length wasm-bytes) summary (wasm-size-text wasm-size)] (if (= wasm-size 0) (do (cli-stderr (standalone-preview1-capability-boundary-message)) (exit-compile-error)) (do (write-file-bytes output-path wasm-bytes) (print-string summary) (print-string "\n") (exit-success)))) (do (cli-stderr (component-output-boundary-message)) (exit-compile-error))) (exit-compile-error)))
(defn run-build-output [file-path output-path opts] (run-compile-output file-path output-path opts))
(defn run-parse [file-path opts] (if (file-exists? file-path) (run-parse-source (read-file file-path) opts) (exit-compile-error)))
(defn run-check [file-path opts] (if (file-exists? file-path) (run-check-source (read-file file-path) opts) (exit-compile-error)))
(defn run-compile [file-path opts] (if (file-exists? file-path) (run-compile-output file-path (default-output-path file-path opts) opts) (exit-compile-error)))
(defn run-build [file-path opts] (if (file-exists? file-path) (run-build-output file-path (default-output-path file-path opts) opts) (exit-compile-error)))
(defn run-test [file-path opts] (if (file-exists? file-path) (run-test-source (read-file file-path) opts) (exit-compile-error)))
(defn run-review [file-path opts] (if (file-exists? file-path) (run-review-source (read-file file-path) opts) (exit-compile-error)))
(defn run-doc-ack [file-path opts] (if (file-exists? file-path) (run-doc-ack-source (read-file file-path) opts) (exit-compile-error)))
(defn run-doc-check [file-path opts] (if (file-exists? file-path) (run-doc-check-source (read-file file-path) opts) (exit-compile-error)))
(defn run-fmt [file-path opts] (if (file-exists? file-path) (run-fmt-source (read-file file-path) opts) (exit-compile-error)))
(defn output-option-flag [arg] (or (string-eq arg "-o") (string-eq arg "--output")))
(defn target-option-flag [arg] (string-eq arg "--target"))
(defn json-option-flag [arg] (string-eq arg "--json"))
(defn format-option-flag [arg] (string-eq arg "--format"))
(defn cli-option-status-ok [] 0)
(defn cli-option-status-invalid-target [] 1)
(defn cli-option-status-missing-value [] 2)
(defn cli-option-status-unsupported-option [] 3)
(defn cli-option-result [status target output-path detail] (let [result (vector-new 4)] (vector-push (vector-push (vector-push (vector-push result status) target) output-path) detail)))
(defn cli-option-result-status [result] (vector-get result 0))
(defn cli-option-result-target [result] (vector-get result 1))
(defn cli-option-result-output-path [result] (vector-get result 2))
(defn cli-option-result-detail [result] (vector-get result 3))
(defn parse-cli-options-loop [idx argc target output-path] (if (>= idx argc) (cli-option-result (cli-option-status-ok) target output-path "") (let [flag (command-line-arg idx)] (if (>= (+ idx 1) argc) (cli-option-result (cli-option-status-missing-value) target output-path flag) (let [flag-value (command-line-arg (+ idx 1))] (if (output-option-flag flag) (parse-cli-options-loop (+ idx 2) argc target flag-value) (if (target-option-flag flag) (let [parsed-target (parse-compile-target-name flag-value)] (if (< parsed-target 0) (cli-option-result (cli-option-status-invalid-target) target output-path flag-value) (parse-cli-options-loop (+ idx 2) argc parsed-target output-path))) (cli-option-result (cli-option-status-unsupported-option) target output-path flag))))))))
(defn parse-cli-options [argc] (parse-cli-options-loop 2 argc (default-compile-target) ""))
(defn review-cli-option-none [] 0)
(defn review-cli-option-invalid [] (- 0 1))
(defn parse-review-cli-option [argc]
  (if (<= argc 2)
    (review-cli-option-none)
    (let [arg2 (command-line-arg 2)]
      (if (and (= argc 3) (json-option-flag arg2))
        (review-option-json)
        (if (= argc 4)
          (if (format-option-flag arg2)
            (if (string-eq (command-line-arg 3) "json")
              (review-option-json)
              (review-cli-option-invalid))
            (review-cli-option-invalid))
          (review-cli-option-invalid))))))
(defn doc-cli-option-none [] 0)
(defn doc-cli-option-invalid [] (- 0 1))
(defn parse-doc-cli-option [argc cmd-name]
  (if (<= argc 2)
    (doc-cli-option-none)
    (let [arg2 (command-line-arg 2)]
      (if (string-eq cmd-name "doc-ack")
        (if (and (= argc 3) (string-eq arg2 "--trailer")) (doc-option-trailer-only) (doc-cli-option-invalid))
        (if (string-eq cmd-name "doc-check")
          (if (and (= argc 3) (string-eq arg2 "--strict")) (doc-option-strict-check) (doc-cli-option-invalid))
          (doc-cli-option-none))))))
(defn run-command-with-doc-option [cmd-name file-path doc-option]
  (let [cmd-id (arg-parse cmd-name)]
    (if (= cmd-id (cmd-doc-ack))
      (run-doc-ack file-path doc-option)
      (if (= cmd-id (cmd-doc-check))
        (run-doc-check file-path doc-option)
        (run-command cmd-name file-path doc-option)))))
(defn run-command [cmd-name file-path opts]
  (let [cmd-id (arg-parse cmd-name)]
    (if (= cmd-id (cmd-parse))
      (run-parse file-path opts)
      (if (= cmd-id (cmd-check))
        (run-check file-path opts)
        (if (= cmd-id (cmd-compile))
          (run-compile file-path opts)
          (if (= cmd-id (cmd-build))
            (run-build file-path opts)
            (if (= cmd-id (cmd-test))
              (run-test file-path opts)
              (if (= cmd-id (cmd-review))
                (run-review file-path opts)
                (if (= cmd-id (cmd-doc-ack))
                  (run-doc-ack file-path opts)
                  (if (= cmd-id (cmd-doc-check))
                    (run-doc-check file-path opts)
                    (if (= cmd-id (cmd-fmt))
                      (run-fmt file-path opts)
                      (exit-compile-error))))))))))))
(defn run-command-with-cli-options [cmd-name file-path result] (let [target (cli-option-result-target result) output-path (cli-option-result-output-path result)] (if (> (string-length output-path) 0) (if (string-eq cmd-name "compile") (run-compile-output file-path output-path target) (if (string-eq cmd-name "build") (run-build-output file-path output-path target) (run-command cmd-name file-path target))) (run-command cmd-name file-path target))))
(defn compile-or-build-command [cmd-name] (or (string-eq cmd-name "compile") (string-eq cmd-name "build")))
(defn run-main-command [argc cmd-name file-path]
  (if (and (compile-or-build-command cmd-name) (> argc 2))
    (let [options (parse-cli-options argc)]
      (if (= (cli-option-result-status options) (cli-option-status-ok))
        (run-command-with-cli-options cmd-name file-path options)
        (exit-compile-error)))
    (if (and (string-eq cmd-name "review") (> argc 2))
      (let [review-option (parse-review-cli-option argc)]
        (if (>= review-option 0)
          (run-command cmd-name file-path review-option)
          (exit-compile-error)))
      (if (and (> argc 2) (or (string-eq cmd-name "doc-ack") (string-eq cmd-name "doc-check")))
        (let [doc-option (parse-doc-cli-option argc cmd-name)]
          (if (>= doc-option 0)
            (run-command-with-doc-option cmd-name file-path doc-option)
            (exit-compile-error)))
        (run-command cmd-name file-path (default-compile-target))))))
(defn exit-main [code] (do (proc-exit code) 0))
(defn main []
  (let [argc (command-line-args)]
    (if (= argc 0)
      (exit-main (exit-compile-error))
      (let [cmd-name (command-line-arg 0)
        file-path (if (> argc 1) (command-line-arg 1) "")]
        (exit-main (run-main-command argc cmd-name file-path))))))
