(module App.Main)
(import App.CompilerMode)
(import App.PipelineSmoke)
(defn main []
  (if (> (string-length (command-line-arg 1)) 0)
    (if (> (string-length (command-line-arg 22)) 0)
      (compile-file-mode-first-defn-source-probe)
      (if (> (string-length (command-line-arg 21)) 0)
        (compile-file-mode-first-defn-source-step-probe)
        (if (> (string-length (command-line-arg 20)) 0)
          (compile-file-mode-ast-chunked-step-progress-probe)
          (if (> (string-length (command-line-arg 19)) 0)
            (compile-file-mode-cache-compile-pair-progress-probe)
            (if (> (string-length (command-line-arg 18)) 0)
              (compile-file-mode-cache-compile-phase-probe)
              (if (> (string-length (command-line-arg 17)) 0)
                (compile-file-mode-warm-target-defn-parity-probe)
                (if (> (string-length (command-line-arg 16)) 0)
                  (compile-file-mode-target-defn-parity-probe)
                  (if (> (string-length (command-line-arg 15)) 0)
                    (compile-file-mode-build-compile-progress-probe)
                    (if (> (string-length (command-line-arg 14)) 0)
                      (compile-file-mode-build-phase-probe)
                      (if (> (string-length (command-line-arg 13)) 0)
                        (compile-file-mode-first-defn-ir-parity-probe)
                        (if (> (string-length (command-line-arg 12)) 0)
                          (compile-file-mode-cache-compile-progress-probe)
                          (if (> (string-length (command-line-arg 11)) 0)
                            (compile-file-mode-expr-tag-debug)
                            (if (> (string-length (command-line-arg 10)) 0)
                              (compile-file-mode-cache-pairs-progress-probe)
                              (if (> (string-length (command-line-arg 9)) 0)
                                (compile-file-mode-cache-pairs-probe)
                                (if (> (string-length (command-line-arg 8)) 0)
                                  (compile-file-mode-cache-probe)
                                  (if (> (string-length (command-line-arg 7)) 0)
                                    (compile-file-mode-token-debug)
                                    (if (> (string-length (command-line-arg 6)) 0)
                                      (compile-file-mode-ir-debug)
                                      (if (> (string-length (command-line-arg 5)) 0)
                                        (compile-file-mode-build-progress-debug)
                                        (if (> (string-length (command-line-arg 4)) 0)
                                          (compile-file-mode-progress-debug)
                                          (if (> (string-length (command-line-arg 3)) 0)
                                            (compile-file-mode-path-debug)
                                            (if (> (string-length (command-line-arg 2)) 0)
                                              (compile-file-mode-debug)
                                              (compile-file-mode)
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
    (run-main-smoke)))
