(module App.ModuleResolver)
(defn text-eq-loop [left right idx len] (if (>= idx len) true (if (= (string-char-at left idx) (string-char-at right idx)) (text-eq-loop left right (+ idx 1) len) false)))
(defn text-eq [left right] (let [len (string-length left)] (if (= len (string-length right)) (text-eq-loop left right 0 len) false)))
(defn same-path [left right] (let [left-len (string-length left) right-len (string-length right)] (if (= left-len right-len) (text-eq-loop left right 0 left-len) false)))
(defn is-src-dir-name [name] (if (= (string-length name) 3) (if (= (string-char-at name 0) 115) (if (= (string-char-at name 1) 114) (= (string-char-at name 2) 99) false) false) false))
(defn path-char [path idx] (string-char-at path idx))
(defn is-path-sep [path idx] (let [ch (path-char path idx)] (if (= ch 47) true (if (= ch 92) true false))))
(defn has-path-sep [path idx len] (if (>= idx len) false (if (is-path-sep path idx) true (has-path-sep path (+ idx 1) len))))
(defn find-last-path-sep [path idx len last] (if (>= idx len) last (find-last-path-sep path (+ idx 1) len (if (is-path-sep path idx) idx last))))
(defn path-parent [path] (let [len (string-length path)] (if (= len 0) "" (if (has-path-sep path 0 len) (let [last (find-last-path-sep path 0 len -1)] (if (< last 0) "" (if (= last 0) "/" (substring path 0 last)))) ""))))
(defn path-basename [path] (let [len (string-length path)] (if (= len 0) "" (if (has-path-sep path 0 len) (let [last (find-last-path-sep path 0 len -1)] (if (< last 0) path (substring path (+ last 1) len))) path))))
(defn path-join [base child] (if (= (string-length base) 0) child (let [len (string-length base)] (if (is-path-sep base (- len 1)) (string-concat base child) (string-concat (string-concat base "/") child)))))
(defn find-src-ancestor [dir] (if (= (string-length dir) 0) "" (if (is-src-dir-name (path-basename dir)) dir (let [parent (path-parent dir)] (if (same-path parent dir) "" (find-src-ancestor parent))))))
(defn find-manifest-root [dir] (if (= (string-length dir) 0) "" (if (file-exists? (path-join dir "lsharp.toml")) dir (let [parent (path-parent dir)] (if (same-path parent dir) "" (find-manifest-root parent))))))
(defn resolve-source-root [entry-path] (let [entry-dir (path-parent entry-path) manifest-root (find-manifest-root entry-dir) src-root (find-src-ancestor entry-dir)] (if (> (string-length src-root) 0) src-root (if (> (string-length manifest-root) 0) (path-join manifest-root "src") entry-dir))))
(defn resolve-package-root [entry-path] (let [entry-dir (path-parent entry-path) manifest-root (find-manifest-root entry-dir) src-root (find-src-ancestor entry-dir)] (if (> (string-length src-root) 0) (path-parent src-root) (if (> (string-length manifest-root) 0) manifest-root entry-dir))))
(defn module-name-to-relative-loop [name idx len out] (if (>= idx len) (string-concat out ".ls") (let [piece (if (= (path-char name idx) 46) "/" (substring name idx (+ idx 1)))] (module-name-to-relative-loop name (+ idx 1) len (string-concat out piece)))))
(defn module-name-to-relative [name] (module-name-to-relative-loop name 0 (string-length name) ""))
(defn module-name-to-index-relative-loop [name idx len out] (if (>= idx len) (string-concat out ".path") (let [piece (if (= (path-char name idx) 46) "/" (substring name idx (+ idx 1)))] (module-name-to-index-relative-loop name (+ idx 1) len (string-concat out piece)))))
(defn module-name-to-index-relative [name] (module-name-to-index-relative-loop name 0 (string-length name) ""))
(defn is-trailing-path-whitespace [text idx] (let [ch (path-char text idx)] (if (= ch 10) true (if (= ch 13) true (if (= ch 32) true (if (= ch 9) true false))))))
(defn trim-trailing-path-whitespace-loop [text end] (if (<= end 0) "" (if (is-trailing-path-whitespace text (- end 1)) (trim-trailing-path-whitespace-loop text (- end 1)) (substring text 0 end))))
(defn trim-trailing-path-whitespace [text] (trim-trailing-path-whitespace-loop text (string-length text)))
(defn resolve-module-path [module-name source-root package-root] (let [nested-rel (module-name-to-relative module-name) local-nested (path-join source-root nested-rel)] (if (= (string-length package-root) 0) local-nested (if (file-exists? local-nested) local-nested (let [index-rel (module-name-to-index-relative module-name) index-root (path-join package-root ".lsharp/module-index") index-path (path-join index-root index-rel) indexed-target (if (file-exists? index-path) (trim-trailing-path-whitespace (read-file index-path)) "") stdlib-root (path-join package-root "stdlib") stdlib-nested (path-join stdlib-root nested-rel)] (if (> (string-length indexed-target) 0) indexed-target (if (file-exists? stdlib-nested) stdlib-nested local-nested)))))))
