use std::fmt::Display;

use miette::Report;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct ErrorCodeEntry {
    pub(crate) code: &'static str,
    pub(crate) legacy_code: Option<&'static str>,
    pub(crate) name: &'static str,
    pub(crate) summary: &'static str,
    pub(crate) detail: &'static str,
    pub(crate) fix: &'static str,
}

pub(crate) const ERROR_REFERENCE_DOC: &str = "docs/guides/error-reference.md";
pub(crate) const DRIVER_IO_ERROR_CODE: &str = "LS5001";

pub(crate) fn driver_io_error(message: impl Display) -> Report {
    miette::miette!("[{DRIVER_IO_ERROR_CODE}] {message}")
}

pub(crate) const ERROR_CODES: &[ErrorCodeEntry] = &[
    ErrorCodeEntry {
        code: "LS0001",
        legacy_code: None,
        name: "unexpected-character",
        summary: "lexer が未知の文字を検出しました",
        detail: "source に L# の token として扱えない文字が含まれています。",
        fix: "該当文字を削除するか、文字列 literal 内へ移動してください。",
    },
    ErrorCodeEntry {
        code: "LS0002",
        legacy_code: None,
        name: "unterminated-string",
        summary: "文字列 literal が閉じていません",
        detail: "lexer が行末またはファイル末尾まで読んでも閉じ quote を見つけられませんでした。",
        fix: "文字列 literal の末尾に `\"` を追加してください。",
    },
    ErrorCodeEntry {
        code: "LS0003",
        legacy_code: None,
        name: "invalid-number",
        summary: "数値 literal の形式が不正です",
        detail: "数値として解釈できない token が数値 literal として現れています。",
        fix: "整数または小数の literal 表記を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS0101",
        legacy_code: None,
        name: "unexpected-token",
        summary: "parser が予期しない token を検出しました",
        detail: "現在の構文位置では受け付けない token が現れました。",
        fix: "括弧の対応、form 名、引数の並びを確認してください。",
    },
    ErrorCodeEntry {
        code: "LS0102",
        legacy_code: None,
        name: "unexpected-eof",
        summary: "source が途中で終了しました",
        detail: "parser が form の途中でファイル末尾に到達しました。",
        fix: "閉じ括弧、vector、metadata form の終端を追加してください。",
    },
    ErrorCodeEntry {
        code: "LS0103",
        legacy_code: None,
        name: "unknown-form",
        summary: "未知の special form です",
        detail: "parser が L# の special form として定義されていない form を検出しました。",
        fix: "`defn`, `type`, `module`, `import`, `trait`, `impl` などの form 名を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS0104",
        legacy_code: None,
        name: "multiple-parse-errors",
        summary: "複数の parse error が発生しました",
        detail: "parser recovery により複数の構文エラーをまとめて報告しています。",
        fix: "先頭の parse error から順に修正してください。",
    },
    ErrorCodeEntry {
        code: "LS0201",
        legacy_code: None,
        name: "macro-expansion-error",
        summary: "マクロ展開に失敗しました",
        detail: "macro の名前、引数、展開深度、または unquote-splicing の文脈を確認してください。",
        fix: "macro 定義と呼び出し引数、quote / unquote の構造を見直してください。",
    },
    ErrorCodeEntry {
        code: "LS1001",
        legacy_code: Some("E0001"),
        name: "undefined-variable",
        summary: "未定義の識別子です",
        detail: "type checker が現在 scope に存在しない変数または関数を参照しました。",
        fix: "定義、import、module path、綴りを確認してください。",
    },
    ErrorCodeEntry {
        code: "LS1002",
        legacy_code: Some("E0002"),
        name: "type-mismatch",
        summary: "型が一致していません",
        detail: "期待型と実際の型が統合できませんでした。legacy E0003 もこの LS1002 に統合します。",
        fix: "if 条件、then/else、関数引数、戻り値の型を揃えてください。",
    },
    ErrorCodeEntry {
        code: "LS1003",
        legacy_code: Some("E0005"),
        name: "infinite-type",
        summary: "無限型が発生しました",
        detail: "型変数が自分自身を含む型へ統合されようとしました。",
        fix: "再帰的自己参照や関数適用の形を見直してください。",
    },
    ErrorCodeEntry {
        code: "LS1004",
        legacy_code: Some("E0004"),
        name: "arity-mismatch",
        summary: "関数引数の個数または型が一致していません",
        detail: "関数型が要求する引数列と呼び出し側の引数列が一致しません。",
        fix: "呼び出し引数の数と型を関数定義に合わせてください。",
    },
    ErrorCodeEntry {
        code: "LS1005",
        legacy_code: None,
        name: "undefined-constructor",
        summary: "未定義の constructor です",
        detail: "ADT constructor が現在 scope に登録されていません。",
        fix: "型定義、import、constructor 名を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS1006",
        legacy_code: None,
        name: "undefined-record",
        summary: "未定義の record 型です",
        detail: "record literal または field access が存在しない record 型を参照しています。",
        fix: "`type Name (record ...)` の定義と import を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS1007",
        legacy_code: None,
        name: "undefined-field",
        summary: "未定義の record field です",
        detail: "record 型に存在しない field を参照しています。",
        fix: "field 名と record 型定義を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS1008",
        legacy_code: None,
        name: "recursive-alias",
        summary: "再帰的な type alias です",
        detail: "type alias が自分自身を直接または間接に参照しています。",
        fix: "再帰が必要な場合は ADT を使い、alias の循環を外してください。",
    },
    ErrorCodeEntry {
        code: "LS1009",
        legacy_code: None,
        name: "undefined-alias",
        summary: "未定義の type alias です",
        detail: "参照された type alias が登録されていません。",
        fix: "alias 定義と import を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS1010",
        legacy_code: None,
        name: "undefined-trait",
        summary: "未定義の trait です",
        detail: "trait constraint または impl が存在しない trait を参照しています。",
        fix: "trait 定義、import、trait 名を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS1011",
        legacy_code: None,
        name: "missing-impl",
        summary: "必要な trait impl が見つかりません",
        detail: "constraint を満たす impl が現在の環境に存在しません。",
        fix: "対象型の impl を追加するか、constraint を見直してください。",
    },
    ErrorCodeEntry {
        code: "LS1012",
        legacy_code: None,
        name: "alias-type-mismatch",
        summary: "type alias 展開後の型が一致していません",
        detail: "alias を展開した型と期待型が統合できませんでした。",
        fix: "alias の target 型と利用箇所の型を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS1013",
        legacy_code: None,
        name: "kind-mismatch",
        summary: "kind が一致していません",
        detail: "型 constructor の kind と適用された型引数の形が一致しません。",
        fix: "型引数の数と高カインド型の使い方を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS2001",
        legacy_code: None,
        name: "legacy-example-migration",
        summary: "legacy :example に canonical migration 候補があります",
        detail: "legacy :example の現在の truthiness semantics を保持したまま、docs-only :example または strict :assert へ移行できます。",
        fix: "report の disposition を確認し、docs-only :example または :assert へ明示的に移行してください。",
    },
    ErrorCodeEntry {
        code: "LS2002",
        legacy_code: None,
        name: "legacy-invariant-migration",
        summary: "legacy :invariant に canonical migration 候補があります",
        detail: "legacy :invariant の deterministic smoke semantics を保持したまま、:property / :postcondition へ移行できます。",
        fix: "binder、generator、postcondition を明示した :property へ移行してください。",
    },
    ErrorCodeEntry {
        code: "LS2003",
        legacy_code: None,
        name: "ambiguous-legacy-contract",
        summary: "legacy contract の意味を安全に自動判定できません",
        detail: "lexical scope または型を確定できないため、classifier は silent conversion を行いません。",
        fix: "参照 scope と意図を確認し、:example、:assert、:case、:property のいずれかを明示してください。",
    },
    ErrorCodeEntry {
        code: "LS2004",
        legacy_code: None,
        name: "empty-executable-contract",
        summary: "executable contract に検査対象がありません",
        detail: ":assert の predicate が空で、検査 0 件を成功として扱う可能性があります。",
        fix: ":assert に Bool predicate を少なくとも 1 件追加してください。",
    },
    ErrorCodeEntry {
        code: "LS2005",
        legacy_code: None,
        name: "vacuous-contract",
        summary: "executable contract が実装の挙動を検査していません",
        detail: ":assert の predicate が静的に常真で、実装差分を検出できません。",
        fix: "実装結果または入力に依存する Bool predicate を指定してください。",
    },
    ErrorCodeEntry {
        code: "LS2006",
        legacy_code: None,
        name: "empty-case-contract",
        summary: "canonical case に検査対象がありません",
        detail: ":case の expectation が空で、テスト 0 件を成功として扱う可能性があります。",
        fix: ":case に actual / expected の組を少なくとも 1 件追加してください。",
    },
    ErrorCodeEntry {
        code: "LS3001",
        legacy_code: None,
        name: "unsupported-lowering",
        summary: "lowering が未対応の構文です",
        detail: "frontend で受理された構文を IR lowering がまだ扱えません。",
        fix: "対応済みの言語機能へ書き換えるか、該当機能の lowering 実装を追加してください。",
    },
    ErrorCodeEntry {
        code: "LS3002",
        legacy_code: None,
        name: "undefined-lowered-function",
        summary: "lowering 後に未定義関数が残っています",
        detail: "IR lowering が解決できない関数参照を検出しました。",
        fix: "module import、関数定義、stdlib 参照を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS3101",
        legacy_code: None,
        name: "cyclic-module-dependency",
        summary: "module dependency に循環があります",
        detail: "module graph が強連結な import cycle を検出しました。",
        fix: "module 境界を分割するか、循環 import をなくしてください。",
    },
    ErrorCodeEntry {
        code: "LS3102",
        legacy_code: None,
        name: "module-not-found",
        summary: "module が見つかりません",
        detail: "import された module path を source root から解決できませんでした。",
        fix: "file path、module 名、package install 状態を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS3103",
        legacy_code: None,
        name: "module-not-exported",
        summary: "module が package から export されていません",
        detail: "package boundary で非公開の module を import しようとしました。",
        fix: "`lsharp.toml` の exports または import 先を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS3104",
        legacy_code: None,
        name: "duplicate-module",
        summary: "module が重複しています",
        detail: "同じ module name を持つ source が複数見つかりました。",
        fix: "source file の配置と module declaration を整理してください。",
    },
    ErrorCodeEntry {
        code: "LS4001",
        legacy_code: None,
        name: "codegen-error",
        summary: "codegen が失敗しました",
        detail: "IR から target artifact を生成する段階でエラーが発生しました。",
        fix: "直前の type / lowering diagnostics と対象 backend の既知制限を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS4002",
        legacy_code: None,
        name: "gc-capacity-exceeded",
        summary: "GC / linear memory の容量上限に達しました",
        detail: "WASI runtime が object table、free-list、root stack、または heap の拡張に失敗しました。",
        fix: "入力の同時生存データ量を減らすか、対応 runtime memory limit と target parity を確認してください。",
    },
    ErrorCodeEntry {
        code: "LS5001",
        legacy_code: None,
        name: "driver-io-error",
        summary: "driver が file I/O に失敗しました",
        detail: "source、生成 artifact、または compile pipeline の管理対象ファイルを読み書きできませんでした。",
        fix: "対象 path の存在、親 directory、権限、空き容量を確認してください。",
    },
];

pub(crate) fn find_error_code(query: &str) -> Option<&'static ErrorCodeEntry> {
    let query = match query {
        "E0003" => "LS1002",
        other => other,
    };
    ERROR_CODES
        .iter()
        .find(|entry| entry.code == query || entry.legacy_code == Some(query))
}
